### ISSUE TITLE
Docs Sidebar

### ISSUE THREAD

**Issue by hzoo** [babel/website#1042]
Copied from https://github.com/babel/babel.github.io/issues/930#issuecomment-256480579

> I think the docs need a sidebar, like the React docs. @danharper 

![screen shot 2016-12-06 at 2 39 37 pm](https://cloud.githubusercontent.com/assets/588473/20940745/d79b0644-bbc1-11e6-835f-4e1d413a591c.png)

```
Primary Nav (left):

* Docs
* Try it out
* Community
* Blog

Secondary Nav (right):

* Twitter
* GitHub
```

Then on the Docs page, the following sidebar:

```
# Quick Start

* Browser
* Node
* Plugins
* Polyfills
* Caveats (or.. Browser Support)
* Editors
* Linting
* Babili (Minification)

# Advanced Usage

* Options
* CLI
* babel-node
* In-Browser Compilation
* Babel API
```

I'm unsure where a "Learn ESXXX" would go, but wherever it goes perhaps just give "highlights" and link off-site for the details. Plenty of community resources for that.

**Comment by bernard-lin** [comment]
Willing to give this a shot! @hzoo

**Comment by existentialism** [comment]
@bernard-lin thanks! join us on slack if you have any questions

**Comment by hzoo** [comment]
This will be done in https://github.com/babel/website/issues/1485 but will iterate
