### ISSUE TITLE
Document operations on AST nodes and path

### ISSUE THREAD

**Issue by xtuc** [babel/website#1160]
For example `path.getSource()` isn't documented yet.

**Comment by xtuc** [comment]
Started writing a documentation about path and node operations: https://gist.github.com/xtuc/26931c424fb7148c000217de8e7fdf76.

**Comment by maurobringolf** [comment]
I have started taking some notes on existing `NodePath` methods as well

https://github.com/maurobringolf/babel/blob/babel-traverse-docs/packages/babel-traverse/README.md

I am not sure what format is most desirable and where all this should go.

**Comment by xtuc** [comment]
We also had a discussion here https://github.com/babel/babel/pull/5717

**Comment by hzoo** [comment]
Moving to https://github.com/babel/website/issues/1628
