### ISSUE TITLE
Performance Improvements (part deux)

### ISSUE THREAD

**Issue by existentialism** [babel/website#1238]
We merged only a part of @denar90's performance optimizations in https://github.com/babel/babel.github.io/pull/1234, which included using `jekyll-assets`.

I think we have to main options here:

- Switch to Cloudflare and use their bundle/optimization stuff (also ref: https://github.com/babel/babel.github.io/pull/1174)

- Switch deployment to build via Travis and commit output to `gh-pages` (or /docs). This definitely opens up additional possibilities for:

  * Replacing submodule usage?
  * A less hacky way of importing READMEs?
  * Other custom plugins.

**Comment by denar90** [comment]
Using Cloudflare also opening some other possibilities like `https`.
I know that @thejameskyle has some experience with that.
Moreover having `https` makes possible using service-workers, which lead to offline stuff.

**Comment by xtuc** [comment]
I made #1239 to track issues with git submodule usage. Not that easy.

**Comment by hzoo** [comment]
Should be fixed now since we download the readmes instead of submodules?
