### ISSUE TITLE
Privacy Badger causes "Babel is not defined"

### ISSUE THREAD

**Issue by athomann** [babel/website#1243]
Privacy Badger causes "Babel is not defined". Not sure if there is anything that can be done to prevent.

<img width="976" alt="screen shot 2017-05-05 at 8 07 40 pm" src="https://cloud.githubusercontent.com/assets/605577/25768247/323248d2-31cf-11e7-96d4-2e56e67b77f3.png">

**Comment by athomann** [comment]
I sent feedback to Privacy Badger.  Seems like they block `unpkg.com` and a few other cnds.

**Comment by xtuc** [comment]
I not sure what I should do in that case.

We could embed Babel build in the website and serve it from it but we'll need to update it manually for each release.

The '[big REPL](https://babeljs.io/repl/)' shouldn't work either.

**Comment by athomann** [comment]
Yes, big  REPL doesn't work either.  Not a big deal for those aware of the side effects of plugins like Privacy badger.  Only will affect those who set it, forget it and then think the site is broken.

**Comment by xtuc** [comment]
In the REPL we could test if `babel` is defined and display a message asking him to check his browser configuration.

This is the first time I hear about that, I can't tell if it's a common issue.

**Comment by hzoo** [comment]
Not really sure this is actionable? going to close
