### ISSUE TITLE
Show latest version number on website

### ISSUE THREAD

**Issue by Daniel15** [babel/website#1248]
What do you think of this?

**Comment by xtuc** [comment]
Like showing the version used in the REPL?

![screenshot from 2017-05-12 11-32-05](https://cloud.githubusercontent.com/assets/1493671/25992396/a5e6e4fe-3706-11e7-8f64-a5633935f079.png)

**Comment by Daniel15** [comment]
Yeah, something like that. See how the Yarn site does it for example: https://yarnpkg.com/

The version in the REPL comes from the `version` property on Babel itself (via babel-standalone). The REPL takes a while to load, so it'd be good to have the version number on the home page somewhere too.

**Comment by xtuc** [comment]
Yes that would be great. How do you update it in Yarn? Since we have two different repo it's a bit trickier, see #1239

**Comment by Daniel15** [comment]
> How do you update it in Yarn?

The version number is stored in `_config.yml`, and part of the automated process for publishing a new release is bumping that number:
https://github.com/yarnpkg/website/blob/master/scripts/set-version.sh
https://github.com/yarnpkg/yarn/blob/master/jenkins_jobs.groovy#L27-L28

This version number is also served from https://yarnpkg.com/latest-version, which is the source of truth for anyone wanting the version number for the latest Yarn version.

**Comment by hzoo** [comment]
Yeah we had it at the bottom of the site a long time ago but it was removed later

**Comment by hzoo** [comment]
Might be covered in https://github.com/babel/website/issues/1485 when we have versions and we create a new version on release?

**Comment by hzoo** [comment]
Moving to https://github.com/babel/website/issues/1633
