### ISSUE TITLE
LICENSE file?

### ISSUE THREAD

**Issue by hausdorff** [babel/website#1251]
It seems that this repository does not contain a LICENSE. I'd like to use a subset of the code, but I need to make sure we're license-compatible. (We are planning to use Apache 2.)

**Comment by j-f1** [comment]
Any update on this? I want to integrate the Babel docs into [DevDocs](https://devdocs.io), but I can’t do that without a license.

**Comment by azz** [comment]
@hzoo Should it be MIT or ISC? (package.json actually says ISC)

**Comment by hzoo** [comment]
Looks like we just didn't add it earlier, but it's MIT ^
