### ISSUE TITLE
Publish syntax and transform doc for numeric separator

### ISSUE THREAD

**Issue by xtuc** [babel/website#1257]
See https://github.com/babel/babel/pull/5793

Edit:
Depends on https://github.com/babel/babel.github.io/pull/1187

**Comment by existentialism** [comment]
Should we just have an umbrella 7.0 task?

**Comment by xtuc** [comment]
I did track tasks in https://github.com/babel/babel.github.io/pull/1187 but an up-to-date issue would be welcome :+1:

**Comment by hzoo** [comment]
It would be better if we could have multi version docs like a lot of other projects. Not sure how it's set up though?

**Comment by xtuc** [comment]
Yes that would be great

**Comment by hzoo** [comment]
I think we have the readme's already so closing
