### ISSUE TITLE
Guest Blog Post: Babel-plugin-preval/babel-macros

### ISSUE THREAD

**Issue by hzoo** [babel/website#1275]
I think it would be interesting to hear from the community on ideas/plugins that add new behavior/etc

Recently both of these have had some attention so it would be great to hear from @kentcdodds about what they are and why via Babel, maybe some more info on implementation?

**Comment by kentcdodds** [comment]
Sure, so to do this I just create a new file [here](https://github.com/babel/babel.github.io/tree/master/_posts) and follow the format of [this one](https://github.com/babel/babel.github.io/blob/master/_posts/2017-03-01-upgrade-to-babel-7.md)? What do I name the file? Is the date the date that it's created or the date it's supposed to be published?

**Comment by hzoo** [comment]
Good question haha.. I'm always confused too, just do created and we'll change it after. Yeah same format for the top part but otherwise do whatever!

**Comment by hzoo** [comment]
https://github.com/babel/website/pull/1277
