### ISSUE TITLE
Make the REPL more usable from a mobile device

### ISSUE THREAD

**Issue by nicolo-ribaudo** [babel/website#1295]
Sometimes I use the repl from the smartphone, but the editor is far too narrow to be usable.
I think there are two things which could improve the UX:
- Make it possible to collapse either the input or the output
- Allow horizontal scrolling on mobile (this is already possible, but you have to use a 1mm-hight invisible scrollbar – at least on Chrome for Android)

**Comment by xtuc** [comment]
Yes, I agree. I'll try to find a few examples. 

Do you want to conrribute to our website?

**Comment by nicolo-ribaudo** [comment]
> Do you want to contribute to our website?

I could work on this next week

**Comment by existentialism** [comment]
@nicolo-ribaudo I'd wait until we land the [react-ified REPL](https://bvaughn.github.io/babel-repl/), if anything.

**Comment by nicolo-ribaudo** [comment]
Ok 👍

**Comment by stephenlcurtis** [comment]
I'm interested in helping if you need assistance.

**Comment by hzoo** [comment]
This is better now right, can close (for repl2)?

**Comment by nicolo-ribaudo** [comment]
Yes
