### ISSUE TITLE
Standardise on one single CDN

### ISSUE THREAD

**Issue by Daniel15** [babel/website#1302]
The Babel site (at least the REPL page) loads assets from **four** different CDNs:
- jsdelivr.net
- cdnjs.cloudflare.com
- unpkg.com
- cdn.rawgit.com

This unnecessarily adds additional DNS lookups and prevents effective use of HTTP/2 pipelining since they're spread across different hostnames.

Let's standardise on a single CDN. unpkg.com might be the best choice for our use cases, as we can load extra stuff from npm packages as needed without having to manually send a PR to configure it like on CDNJS. @mjackson seems pretty responsive to feedback too.

Edit: Huh, interesting, jsdelivr supports loading any npm package now too, just like unpkg. https://www.jsdelivr.com/

**Comment by xtuc** [comment]
Yes I agree, and I introduced bundle.run to browserify some presets used in the REPL. I will maintain this service, if you're ok with that we can stick with it.

**Comment by hzoo** [comment]
I like unpkg, we don't need to bundle once we move babel-standalone into the repo. For plugins outside the repo we can just use what other services like codesandbox do?

**Comment by Daniel15** [comment]
A service like bundle.run is going to add extra overhead which isn't
necessary for most CSS and JS files that we're loading from the CDN.
Browserify/Webpacking on the fly is pretty slow. I'd be fine keeping it for
things that need it, but in other cases I think we should use a regular
CDN.

Sent from my phone.

On Aug 8, 2017 5:07 AM, "Henry Zhu" <notifications@github.com> wrote:

I like unpkg, we don't need to bundle once we move babel-standalone into
the repo. For plugins outside the repo we can just use what other services
like codesandbox do?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/babel/babel.github.io/issues/1302#issuecomment-320936216>,
or mute the thread

**Comment by mjackson** [comment]
Hey y'all, happy you're considering using unpkg :) Also happy to answer any questions you may have about it. I'll be doing quite a bit of work on the service this week. Prepping for some interesting new features :)

**Comment by xtuc** [comment]
Sorry I meant in addition of unpkg. bundle.run could give us the possibility to support community plugins (like babel-preset-php). The first request is slow because of the bundle process but then It cached and fast to access.

Thanks @mjackson :+1:

**Comment by Daniel15** [comment]
Oh cool, that makes sense. 

The issue I've seen with services like bundle.run is that they always bundle everything and don't let you specify external modules. That means that a Babel preset would bundle the whole of Babel with it. We might need to fork one of them and modify it to handle it. 

_Sent from my Samsung SM-G950U using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by xtuc** [comment]
Yes right.
We can submit a feature request for specifying externals to @Rich-Harris.

**Comment by Daniel15** [comment]
There's actually a **fourth** CDN that I didn't notice initially:
```
https://cdn.rawgit.com/thejameskyle/slick/lazy-load-responsive-2/slick/slick.min.js
```

So many CDNs o_o

**Comment by hzoo** [comment]
Don't remember if we changed this since then

**Comment by Daniel15** [comment]
I think jsdelivr and cdn.rawgit.com are gone now, but we're still using both CDNJS and Unpkg. That's better but maybe we should just use Unpkg for everything.

**Comment by hzoo** [comment]
![image](https://user-images.githubusercontent.com/588473/38911139-370d120a-429b-11e8-83c2-7aeb299b00fc.png)

Ok these 2 places look easy to fix/change.
