### ISSUE TITLE
Hook js/repl into Jekyll/make build process

### ISSUE THREAD

**Issue by bvaughn** [babel/website#1309]
Configure `make build` to run REPL `yarn build` (in `js/repl`) and `make watch` to run `yarn start`.

The result of `yarn build` should be synced to `_site/repl`. The contents of `js/repl` should _not_ however.

This is a follow-up item for PR #1297

**Comment by bvaughn** [comment]
cc @hzoo to add this to the ["New REPL" milestone](https://github.com/babel/website/milestone/1). (I don't have permissions to.)

**Comment by Daniel15** [comment]
Working on this!

**Comment by Daniel15** [comment]
https://babeljs.io/repl2/

Same as before, `make serve` to run it locally. It'll run both Webpack **and** Jekyll concurrently.
