### ISSUE TITLE
Run Flow and Prettier via precommit hook

### ISSUE THREAD

**Issue by bvaughn** [babel/website#1310]
Run `yarn flow` and `yarn prettier` as part of precommit hook (or a CI check).

Currently, Prettier is setup to run against `js/repl` only but it would be nice if it ran against all of the Babel JS.

This is a follow-up item for PR #1297

**Comment by bvaughn** [comment]
cc @hzoo to add this to the ["New REPL" milestone](https://github.com/babel/website/milestone/1). (I don't have permissions to.)

**Comment by Daniel15** [comment]
I accidentally removed them in https://github.com/babel/website/pull/1320 but we can add them to the root `package.json` and run them across the entire site. TravisCI already runs some lint checks, it could run ESLint/Prettier/Flow checks too.

**Comment by Andarist** [comment]
I can help with that. Gonna send a PR some time later today
