### ISSUE TITLE
REPL should lazy-load Babel standalone from CDN

### ISSUE THREAD

**Issue by bvaughn** [babel/website#1313]
Lazy-load Babel standalone from CDN as well to better support loading different versions of Babel.

We'll have to decide how to handle compatibility with presets as well as other tools (eg Prettier).

This is a follow-up item for PR #1297

**Comment by bvaughn** [comment]
cc @hzoo to add this to the ["New REPL" milestone](https://github.com/babel/website/milestone/1). (I don't have permissions to.)

**Comment by Daniel15** [comment]
Basically, reimplement this PR in the new REPL: https://github.com/babel/website/pull/1284
