### ISSUE TITLE
"Try it out" menubar item should be selected when on new REPL

### ISSUE THREAD

**Issue by Daniel15** [babel/website#1324]
https://babeljs.io/repl/ -> "Try it out" is selected.
https://babeljs.io/repl-old/ -> "Try it out" is not selected.
https://babeljs.io/php -> "Try it out" is not selected.

**Comment by xtuc** [comment]
The selection of the correct item in the menu is [here](https://github.com/babel/website/blob/master/_includes/header.html#L43). The `page.url contains item.url` adds so much restrictions, it's not the first time we have this kind of issues.

**Comment by hzoo** [comment]
Closed by https://github.com/babel/website/pull/1603!
