### ISSUE TITLE
Nicer loading state for new REPL

### ISSUE THREAD

**Issue by Daniel15** [babel/website#1325]
While the JS is loading, the new REPL just shows some plain "Loading" text at the top left. Let's add a slightly nicer loading state - At least bigger text and centered, or something like that. I'm not a designer 😛

**Comment by bvaughn** [comment]
I think we can probably use a similar UI treatment as was added in #1318.

![loading](https://user-images.githubusercontent.com/29597/29473877-47a9c6ae-840e-11e7-83ed-a8aff097d187.gif)

**Comment by Daniel15** [comment]
Good idea. We should be able to update that loading state to use plain CSS (and maybe a bit of JS) so it can be used as a loading indicator for the entire REPL.

**Comment by bvaughn** [comment]
Agreed!
