### ISSUE TITLE
Sanitize evaluated input

### ISSUE THREAD

**Issue by bvaughn** [babel/website#1329]
Copying one of the examples from the [React "getting started" guide](https://facebook.github.io/react/docs/introducing-jsx.html) and enabling "evaluate" actually un-mounts the REPL and replaces it with the example code. ([Here is an example](http://babeljs.io/repl2/#?babili=false&browsers=&builtIns=false&code_lz=GYVwdgxgLglg9mABMOAnAtgQygOU-gUwAoQBnA1ASkQG8AoRRVAqEVJMigOmBlVNz4CiANSIA5BNGJOqLgBtMAvIQDcdAL506EBAJnlUiALy0GyPsqEAuCQAlMqAA4VxAGnOKrhW-IAKFAQAXuKa6jp6UIgE8gSEYFGmROYAPAAWAIwAfOaMdjHycG60KBjYKsSylBoAhKkA9Jk5lOEASgSY0AAiAPIAslzMYAAmFMmMMXEECR6Mw3AQIPFQXADmLACiscsAQgCeAJLDROKocHBQ4pR0LUA&debug=false&evaluate=true&lineWrap=false&presets=es2016%2Creact&prettier=false&showSidebar=true&targets=).)

**Comment by Daniel15** [comment]
Hahahaha. Wonderful.

To be fair, the old repo also has the same problem if you do something like `document.body.innerHTML = 'lol'`. I wonder if it should either shim `document` and `window`, or evaluate the script in an iframe.

**Comment by bvaughn** [comment]
Follow up with eval in an iframe.

**Comment by bvaughn** [comment]
This was moved into an `<iframe>` via #1315
