### ISSUE TITLE
Convert REPL sidebar to accordion view

### ISSUE THREAD

**Issue by bvaughn** [babel/website#1347]
It's already a bit cramped and this will only get worse once issues like #858 and #1292 are added.

I propose a design similar to what CodeSandbox.io uses:
<img width="431" alt="screen shot 2017-08-27 at 4 25 26 pm" src="https://user-images.githubusercontent.com/29597/29754932-5d184262-8b44-11e7-8678-f4fa846ad940.png">

It should provide us lots of room to grow.

**Comment by hzoo** [comment]
sounds good to me
