### ISSUE TITLE
Try links doesn't work with the new REPL

### ISSUE THREAD

**Issue by xtuc** [babel/website#1349]
When clicking on the "Try" link in http://babeljs.io/learn-es2015/#ecmascript-2015-features-destructuring the REPL opens without the content of the code snippets.

Does the content in URL conflicts with my cached content somehow? I think it should override but still keep the cached code in the local storage.

@bvaughn any idea?

Edit:
it doesn't work in incognito mode, it's not cache related.

**Comment by bvaughn** [comment]
Interesting!

[Query/URL state always overrides `localStorage` state](https://github.com/babel/website/blob/5ad2023f39e63a6c3b49bba8a2faa7bdcb91d54b/js/repl/replUtils.js#L33-L38) if present. This was an intentional design choice.

I'll look into why this is happening!

**Comment by bvaughn** [comment]
Ah, the cause of this is that the "Try" links aren't compressing the code in the way the REPL expects. I was unaware of this use-case. I'll put up a PR fix momentarily!
