### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by montogeek** [babel/website#135]
Is there any plans to translate the docs to others languages?

**Comment by sebmck** [comment]
Not currently, I don't speak any languages other than English (I know basic Japanese, konichiwa) and I don't think @thejameskyle does either.

**Comment by thejameskyle** [comment]
We recently started translating the Marionette documentation to other languages, I'll let you know how that goes and we could adopt the same process.

**Comment by montogeek** [comment]
The PHPLeague docs (https://github.com/thephpleague/thephpleague.github.io) also uses Jekyll and all its content is translated, is an example how it can be done

**Comment by thejameskyle** [comment]
Oh that's really nice.

**Comment by sebmck** [comment]
The problem is going to be getting someone to translate it in the first place and then subsequently maintain it.

**Comment by thejameskyle** [comment]
Yeah, we can see about getting setup with something like transifex.

**Comment by montogeek** [comment]
I can help with the Spanish translation. I'm sure there are another people happy to help!

**Comment by arthurvr** [comment]
> The problem is going to be getting someone to translate it in the first place and then subsequently maintain it.

Translations are super hard to maintain. If you end up having them, limit them to a few languages. I worked on some site where we just removed them after a while. Stuff gets outdated way to quick.

**Comment by Daniel15** [comment]
We use Crowdin for the Yarn site. Works well.

**Comment by hzoo** [comment]
Moving to https://github.com/babel/website/issues/1619
