### ISSUE TITLE
REPL docs

### ISSUE THREAD

**Issue by hzoo** [babel/website#1359]
After https://github.com/babel/website/pull/1356

- how do we document this url structure to users? do we make a docs page, a tooltip somewhere, explain the structure so people will know about it?
- and can we link to the PR that caused that build (circular reference back), or link to the commit/branch tip for easy checking?

cc @Daniel15

**Comment by existentialism** [comment]
We could have a modal come up if they click on the version in the sidebar, that can offer switching between major versions, describe URL options (not sure if we _really_ need to do this tho), and if applicable, link back to PR?

**Comment by hzoo** [comment]
that would be fun lol, or have a tooltip on hover of the version (or we can put it in the error message) at the bottom

**Comment by existentialism** [comment]
Yea, either way it needs to be pretty unobtrusive IMO, the REPL is _only_ going to continue to get more complicated.

**Comment by hzoo** [comment]
Yeah I would move all of it into version (on click/hover) if we do it

**Comment by hzoo** [comment]
would be nice to just emulate the github url naming

**Comment by hzoo** [comment]
don't think this is as big a deal anymore
