### ISSUE TITLE
babel-plugin-transform-regenerator is always enabled

### ISSUE THREAD

**Issue by nicolo-ribaudo** [babel/website#1369]
http://babeljs.io/repl#?babili=false&browsers=&build=&builtIns=false&circleciRepo=&code_lz=IYZwngdgxgBAZgV2gFwJYHsLwgCgJQwDeAvgFCIoYQBU2ATPkcUA&debug=false&evaluate=false&lineWrap=false&presets=&prettier=false&showSidebar=true&targets=&version=6.26.0

## Input code
```js
async function fn() {}
function* fn2() {}
```

## Settings/Presets
Everything should be unchecked

## Screenshot

![babel-repl-bug-regenerator](https://user-images.githubusercontent.com/7000710/30063850-4a2f3daa-9250-11e7-90c7-39418b4bece1.png)

**Comment by loganfsmyth** [comment]
@bvaughn Looks like this from https://github.com/babel/website/commit/c10d2e95267e325713269501c5801bb468810470#diff-6cc3e83f602a8e0e95c6eddfb8bb6a79R31

Did that get added in there for a reason, or was that a mistake?

**Comment by bvaughn** [comment]
Don't know if it was intentional or not. Doesn't seem ideal though.
