### ISSUE TITLE
Make a team page

### ISSUE THREAD

**Issue by hzoo** [babel/website#1381]
It's cool that I added this earlier but we don't really update it and it's probably better on the website anyway 

https://github.com/babel/babel/blob/745c4740af136fa590c829cf435c60e6413a8952/README.md#core-members

Can also put more information, like how you got involved, what you like to work on, etc

**Comment by rajzshkr** [comment]
@hzoo I can pick this.

**Comment by xtuc** [comment]
Good news @rajzshkr, you can join our Slack if you have any question or need some help.

**Comment by rajzshkr** [comment]
@xtuc where can I get the design?

**Comment by hzoo** [comment]
We don't have a design, I would just go with something like https://vuejs.org/v2/guide/team.html

**Comment by hzoo** [comment]
Started in https://github.com/babel/website/pull/1429, needs descriptions but it's done
