### ISSUE TITLE
Sidebar navigation overlays community discussion on docs

### ISSUE THREAD

**Issue by jakegavin** [babel/website#1382]
Currently, the sidebar navigation covers up the community discussion section:
![image](https://user-images.githubusercontent.com/5965895/30565534-807b5754-9c7d-11e7-9e42-9c3cd9157a60.png)

One way to resolve this would be to change the [docs layout](https://github.com/babel/website/blob/f7ac556ef1e392b7c1a4351b94820ac9ba0c4441/_layouts/docs.html) so that the community discussion section is inside the `<div class="col-md-9 docs-conent">`. It'd roughly look like:
![image](https://user-images.githubusercontent.com/5965895/30565631-eedba5b4-9c7d-11e7-96cf-eb1afbe3bd53.png)

If that seems like a good approach, I'm happy to open a PR.

**Comment by hzoo** [comment]
Was thinking we should just remove or move to github comments instead, will need to reimplement in https://github.com/babel/website/pull/1521 so closing for now
