### ISSUE TITLE
REPL is broken

### ISSUE THREAD

**Issue by umar-xgrid** [babel/website#1384]
[The page](https://babeljs.io/repl/) keeps showing a throbber indefinitely. Says "Uncaught ReferenceError: React is not defined" in console.

<img width="1440" alt="screen shot 2017-09-19 at 3 47 53 pm" src="https://user-images.githubusercontent.com/31015073/30589006-5c5059bc-9d52-11e7-903b-cf98d8dbe4de.png">

**Comment by kasiriveni** [comment]
@umar-xgrid  its working fine now

**Comment by hzoo** [comment]
one of the cdn we use might of been down at the time
