### ISSUE TITLE
Question about inheritance (precisely about instantiating superclass object)

### ISSUE THREAD

**Issue by aaaia** [babel/website#1385]
I have a question.

I pasted code below to Your translator (https://babeljs.io/repl)

     class A {
       constructor(a){console.log(a);}
     } 

     class B extends A {
         constructor(b){
             super(b)
         }
    }

And the result was:

    "use strict";
    
    function _possibleConstructorReturn(self, call) { if (!self) { throw new ReferenceError("this hasn't been initialised - super() hasn't been called"); } return call && (typeof call === "object" || typeof call === "function") ? call : self; }
    
    function _inherits(subClass, superClass) { if (typeof superClass !== "function" && superClass !== null) { throw new TypeError("Super expression must either be null or a function, not " + typeof superClass); } subClass.prototype = Object.create(superClass && superClass.prototype, { constructor: { value: subClass, enumerable: false, writable: true, configurable: true } }); if (superClass) Object.setPrototypeOf ? Object.setPrototypeOf(subClass, superClass) : subClass.__proto__ = superClass; }
    
    function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }
    
    var A = function A(a) {
        _classCallCheck(this, A);
    
        console.log(a);
    };
    
    var B = function (_A) {
        _inherits(B, _A);
    
        function B(b) {
            _classCallCheck(this, B);
    
            return _possibleConstructorReturn(this, (B.__proto__ || Object.getPrototypeOf(B)).call(this, b));
        }
    
        return B;
    }(A);
    

I can not uderstand why superclass object is instantiated from superclass prototype `((B.__proto__ || Object.getPrototypeOf(B)).call(this, 2))` whitout super class constructor (ex.: `B.apply(this,[2])`).

In such way code in superclass constructor (A) is never executed, because i have impression that subclass constructor created in _inherits method is overriden by constructor function in B class.

PS. sorry if this is not right place to post such question

**Comment by nicolo-ribaudo** [comment]
`if (superClass) Object.setPrototypeOf ? Object.setPrototypeOf(subClass, superClass) : subClass.__proto__ = superClass;` in `_inherits` sets B's __proto__ object to A.
It's `B.prototype.constructor` that is overridden, not `B.__proto__` (which is returned by `getPrototypeOf`).

PS. If you have other questions, you can ask in our slack channel (https://babeljs.slack.com)

**Comment by aaaia** [comment]
Thanks for quick reply.
