### ISSUE TITLE
REPL: remove parts of the url that are falsy/empty since unncessary

### ISSUE THREAD

**Issue by hzoo** [babel/website#1402]
So for a url like

`https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&code_lz=IZA&debug=false&circleciRepo=&evaluate=false&lineWrap=true&presets=es2015-loose&targets=&version=7.0.0-beta.0`

Some of the fields that are either `&key=` or `&key=false` can be removed and it should work the same?
`babili=false&browsers=&build=&builtIns=false&debug=false&circleciRepo=&evaluate=false&targets=`

This is because we don't have default true/false so not setting false should be ok. Basically then we can have a shorter url

(unless we create a button somewhere to shorten the url or something)

**Comment by Daniel15** [comment]
Instead of stripping `false`, we should strip params that have the default value. It's possible we already have params that default to `true`, or might in the future.

**Comment by hzoo** [comment]
Much better idea ^, thanks Daniel 😄

**Comment by rajzshkr** [comment]
I can pick this.

**Comment by rajzshkr** [comment]
has PR #1441

**Comment by bvaughn** [comment]
> Some of the fields that are either &key= or &key=false can be removed and it should work the same?

> This is because we don't have default true/false so not setting false should be ok. Basically then we can have a shorter url

I have concerns about this proposed change, as mentioned [in this comment](https://github.com/babel/website/pull/1441/#discussion_r147421106).
