### ISSUE TITLE
REPL: keybindings don't work

### ISSUE THREAD

**Issue by hzoo** [babel/website#1409]
Got informed by @designjockey that the keybindings don't work anymore in the new REPL!!

This is weird because we did set the keyMap so not sure what is wrong?
 https://github.com/babel/website/blob/54bf885ef07a418b48561a9a82f6a192eba5d078/js/repl/CodeMirror.js#L10

Example of it working: https://codemirror.net/demo/sublime.html.

Example is being able to do `ctrl+/` for commenting a selection

**Comment by existentialism** [comment]
Let's close this and file separate issues for any additional specific keyboard shortcuts we want to enable.
