### ISSUE TITLE
Design the Videos Page (and add more links)

### ISSUE THREAD

**Issue by hzoo** [babel/website#1418]
Update https://github.com/babel/website/blob/master/docs/community/videos.md

Other vids?

- https://www.youtube.com/watch?v=VBscbcm2Mok&index=3&list=PLV5CVI1eNcJgNqzNwcs4UKrlJdhfDjshf
- https://youtu.be/rpb9iOKyO30
- https://www.youtube.com/watch?v=wo8ZLdveIcI&t=10s&list=PLtAjOQfgHj2W7vDBcfcM99ZCUm39jkefR&index=7

**Comment by existentialism** [comment]
Would be great too if someone would take a stab at redesigning how the videos are displayed, maybe something like:

![image](https://user-images.githubusercontent.com/56288/31578682-e1dc7334-b0eb-11e7-9ed3-b99cc8bbfb50.png)

**Comment by xtuc** [comment]
It looks really cool @existentialism. 

We could probably make a beginner-friendly issue for this?

**Comment by hzoo** [comment]
Oh nice! Actually yeah we could just make it a data thing like the users and generate the format ^ https://github.com/babel/website/blob/master/_data/users.yml

**Comment by ishankbahl** [comment]
I would like to work on this one. Is any component library or package to be used for this component?

**Comment by existentialism** [comment]
@ishankbahl thanks for offering, it looks like @zsoltime has put a PR up! would you like to help review it?
