### ISSUE TITLE
[team] missing V8 collabs

### ISSUE THREAD

**Issue by xtuc** [babel/website#1444]
We are happy to have a few V8 members as Babel collaborators:
- https://github.com/fhinkel
- https://github.com/gsathya
- https://github.com/bmeurer

I think we would be great to add a special group for the V8 team on our [team page on the website](https://babeljs.io/team).

**Comment by azz** [comment]
Should `@gsathya` be under V8 or TC39?

**Comment by xtuc** [comment]
that a good question.

Let's ask @gsathya :)

**Comment by azz** [comment]
@littledan and @mathiasbynens, too :P

**Comment by xtuc** [comment]
Yes, that's right. I not sure what we should do here.

**Comment by littledan** [comment]
I'm happy to stay as TC39.

**Comment by xtuc** [comment]
@azz found a better solution. We can now assign multiple teams to one person.
