### ISSUE TITLE
Babelify missing install of babel-core

### ISSUE THREAD

**Issue by jon-a-nygaard** [babel/website#1452]
1. Go to https://babeljs.io/docs/setup/
2. Choose Browserify

Under the section "Installation" it says:
```
npm install --save-dev babelify
```
While I believe it should be as in https://github.com/babel/babelify#installation
where it says the following:
```
npm install --save-dev babelify babel-core
```

**Comment by BitYog** [comment]
@loganfsmyth @jon-a-nygaard It can be done, but the HTML element for this imports from tools/items.md. I can't even see this folder in docs/. Where can I find this folder?

**Comment by existentialism** [comment]
@BitYog this already has a PR open for it, check out https://github.com/babel/website/pull/1455/files!

**Comment by BitYog** [comment]
That's alright. Thanks @existentialism

**Comment by AkshatSrivastava2** [comment]
@existentialism  Is this issue closed? I wanted to work with this.
