### ISSUE TITLE
Document missing babel 7 breaking changes

### ISSUE THREAD

**Issue by danez** [babel/website#1477]
This is just a list of things i run into when upgrading to babel 7 that are not yet documented:

- [ ] The config key `babelrc: false/true` can now only be used when using the node-api or everything wrapping the node api like webpack options for babel-loader. It cannot be used in presets or babelrc files.
- [x] ~~preset-env does not transform `import "core-js";` anymore when using `builtIns: "entry"`. Need to be changed to `import "@babel/polyfill";` (Maybe change that?)~~ we added this back
- [ ] `@babel/template` is now handling replacements different and assumes every identifier in the template that is uppercase is a placeholder. So templates that include uppercase identifiers like `process.env.NODE_MODULES` need to set the `placeholderPattern` and include exactly all placeholders to replace. See babel/babel#7035
- [x] Document the name change from `transform` to `proposal` for some packages. Maybe include a mapping of old package name -> new package name
- [x] getFunctionParent() no longer returns program scope https://github.com/babel/babel/pull/5923
- [ ] Replace instead of merging babel-register options, and resolve cwd up front https://github.com/babel/babel/pull/7416

**Comment by hzoo** [comment]
- `sourceMapTarget` is removed from `@babel/core: https://github.com/babel/babel/pull/7500
- spec: throw if array rest/spread isn't iterable https://github.com/babel/babel/pull/7491
- `ast: false` is default in `@babel/core` https://github.com/babel/babel/pull/7436
- `sourceType` determines module/script https://github.com/babel/babel/pull/7417
- setters cannot have rest https://github.com/babel/babel/pull/7498
- cjs options https://github.com/babel/babel/pull/7545

**Comment by edmorley** [comment]
* `@babel/preset-env` no longer accepts `useBuiltIns: true` - with that now being equivalent to `useBuiltIns: 'entry'`, and there being a new option `useBuiltIns: 'usage'` (which is recommended?)
* `@babel/preset-env` now sets `useBuiltIns: true` for plugins it activates, if it was set to `'usage'` or `'entry'` for preset-env (this part wasn't too clear in the preset-env README; I had to read the source)
