### ISSUE TITLE
Github link on plugin pages are broken

### ISSUE THREAD

**Issue by nguyenj** [babel/website#1481]
![class properties transform babel 2017-12-12 07-04-29](https://user-images.githubusercontent.com/1127677/33891426-c26b4898-df0a-11e7-8f76-cbb08bbbfd87.png)

It's currently located here, 
[https://github.com/babel/babel/tree/master/packages/babel-plugin-**proposal**-class-properties](https://github.com/babel/babel/tree/master/packages/babel-plugin-proposal-class-properties), 
**not here**, 
[https://github.com/babel/babel/tree/master/packages/babel-plugin-**transform**-class-properties](https://github.com/babel/babel/tree/master/packages/babel-plugin-transform-class-properties).

**Comment by hzoo** [comment]
This is a result of master being on v7 where we renamed some packages, will be fixed once we land https://github.com/babel/website/pull/1521 and more
