### ISSUE TITLE
transform-remove-console docs inconsistent with published package

### ISSUE THREAD

**Issue by hkrutzer** [babel/website#1484]
https://babeljs.io/docs/plugins/transform-remove-console/ mentions plugin options: `{ "exclude": [ "error", "warn"] }`, but these are not actually usable because the published package, https://www.npmjs.com/package/babel-plugin-transform-remove-console, does not yet contain these options. Following the steps to install the plugin on https://babeljs.io/docs/plugins/transform-remove-console/ and adding an exclude option does not work. I think the plugin docs should be consistent with the latest published package.

**Comment by hzoo** [comment]
Same as issue as others - our docs are on v6 while v7 is master - showing the latest version might be just as confusing but we are working on versioned docs via https://github.com/babel/website/pull/1521
