### ISSUE TITLE
include/exclude preset-env option for the REPL

### ISSUE THREAD

**Issue by yavorsky** [babel/website#1497]
https://github.com/babel/website/pull/1415 in progress, which is actually aimed at extending preset-env options.
There are many features that still weren't implemented, and one of them is include/exclude plugins. 

Also, REPL is not ar rubber and we need to keep just most useful of features, so do we need an include/exclude preset options?
We could have something like `AccordionTab` with already registered plugins or just handle it with text inputs.

I don't know if it would be useful at all. And if so, I could add it to the https://github.com/babel/website/pull/1415

**Comment by hzoo** [comment]
Moving to https://github.com/babel/website/issues/1292
