### ISSUE TITLE
Translation does not run

### ISSUE THREAD

**Issue by pgorbas** [babel/website#1499]
I needed to convert the following line of code that works everywhere (Chrome, Firefox, Opera, Edge) except Internet explorer; so I needed it to run everywhere including IE.

So this line:
```var foundState = $scope.States.find(o => o.Abbreviation === uspsStateCode);```

was converted to
```
var foundState = $scope.States.find(function (o) {
          return o.Abbreviation === uspsStateCode;
        });
```
which runs NOWHERE.

P.S.  I see no install instructions for Visual Studio.  Running in the Browser it is very difficult to copy the translated solution.

**Comment by nicolo-ribaudo** [comment]
Why it doesn't run? Which error does it throw? It looks correct.

**Comment by loganfsmyth** [comment]
That would throw if you aren't loading `babel-polyfill` since `.find` is a prototype method, and the default transforms only cover syntactic additions to the language. I'm not sure what you mean by "NOWHERE", since that could will absolutely run anywhere the original code does.

**Comment by hzoo** [comment]
This is unrelated to the Babel website.

The arrow function transform is correct and most likely the error is about using `.find` like mentioned ^.
