### ISSUE TITLE
New Site: Videos page

### ISSUE THREAD

**Issue by hzoo** [babel/website#1522]
Part of https://github.com/babel/website/pull/1521
> aside: maybe we need a resources page which links to podcasts as well or we rename it to media? I guess we could do a similar thing for articles/blog posts/books/etc.

We need to port the [videos](https://babeljs.io/docs/community/videos/) page in the new site since the old one used jekyll (`{% for category in site.data.videos %}`) and bootstrap css

This would be targeting the [`docusaurus`](https://github.com/babel/website/tree/docusaurus) branch, not master.

> I would read through some of the docs: https://docusaurus.io/docs/en/installation.html + and check out the branch

- [ ]  we need to basically convert the [videos](https://github.com/babel/website/blob/docusaurus/videos.html) page into a react component and put it into [website/pages/en](https://github.com/babel/website/tree/docusaurus/website/pages/en) as `videos.js`
- [ ] should probably move the [data](https://github.com/babel/website/blob/docusaurus/_data/videos.yml) into it's own file or just in the video.js file itself (doesn't matter to me right now).
- [ ] will need to re-create/create styling for that page: current styling at https://github.com/babel/website/blob/docusaurus/_sass/components/_video.scss. Totally fine if you can improve on what's there as well so it doesn't "have" to look the same

- So move https://github.com/babel/website/blob/docusaurus/videos.html + https://github.com/babel/website/blob/docusaurus/_data/videos.yml into a `https://github.com/babel/website/blob/docusaurus/website/pages/en/videos.js`

cc @zsoltime since you made the page originally if you want to do this or we can ask someone new!

**Comment by QC-L** [comment]
@hzoo Hi,  I would like to take up this issue, will be submitted as soon as possible.

**Comment by hzoo** [comment]
Via https://github.com/babel/website/pull/1524
