### ISSUE TITLE
New Site: Team page

### ISSUE THREAD

**Issue by hzoo** [babel/website#1523]
Basically the same idea as in https://github.com/babel/website/issues/1522

We need to port the [team](https://babeljs.io/team) page in the new site since the old one used jekyll (`{% for category in site.data.team %}`) and bootstrap css

This would be targeting the [`docusaurus`](https://github.com/babel/website/tree/docusaurus) branch, not master.

> I would read through some of the docs: https://docusaurus.io/docs/en/installation.html + and check out the branch

- [ ]  we need to basically convert the [team](https://github.com/babel/website/blob/docusaurus/team.md) page + https://github.com/babel/website/blob/docusaurus/_includes/member.html into a react component and put it into [website/pages/en](https://github.com/babel/website/tree/docusaurus/website/pages/en) as `team.js`
- [ ] should probably move the [data](https://github.com/babel/website/blob/docusaurus/_data/team.yml) into a different file or just in the team.js file itself (doesn't matter to me right now).
- [ ] will need to re-create/create styling for that page: current styling at https://github.com/babel/website/blob/docusaurus/_sass/pages/_team.scss. Totally fine if you can improve on what's there as well so it doesn't "have" to look the same

cc @rajzshkr since you had worked on this originally but open to other help

EDIT: would be nice to include https://github.com/babel/website/issues/1457 too (an area for each team member to say something)

**Comment by abiduzz420** [comment]
Hi @hzoo This is a wonderful opportunity for contribution to babel ecosystem. I would like to take up this issue. Right now, just figuring out different things in the new branch Docusaurus.

**Comment by hzoo** [comment]
Closed by https://github.com/babel/website/pull/1530
