### ISSUE TITLE
New Site: 404 page

### ISSUE THREAD

**Issue by hzoo** [babel/website#1526]
Part of https://github.com/babel/website/pull/1521

> Should be simple enough to just make a 404.js in `website/pages/en`
> Ref https://github.com/facebook/Docusaurus/issues/301

This would be targeting the [`docusaurus`](https://github.com/babel/website/tree/docusaurus) branch, not master.

> I would read through some of the docs: https://docusaurus.io/docs/en/installation.html + and check out the branch

Might be fun to make it show the ascii guy fieri or something but feel free to just port https://github.com/babel/website/blob/master/404.html for now and we can move forward

**Comment by GregBorrelly** [comment]
Hello, I would like to take over this issue.

**Comment by hzoo** [comment]
@GregBorrelly still planning on tackling this?

**Comment by GregBorrelly** [comment]
@hzoo pushing a PR request tonight. Got caught up with work on the weekend.

**Comment by GregBorrelly** [comment]
@hzoo so far I created the 404.js page with the following code in it 
`const React = require('react');


const ErrorPage = props => {

    return (
        <div className="container">
            <div className="row">
                <div className="col-md-8 col-md-push-2">
                    <script type="text/javascript">
                        var GOOG_FIXURL_LANG = 'en';
                        var GOOG_FIXURL_SITE = 'https://babeljs.io/'
                     </script>
                    <script type="text/javascript" src="https://linkhelp.clients.google.com/tbproxy/lh/wm/fixurl.js"></script>
                </div>
            </div>
        </div>
    )
}`

How can I check out how this page looks?  Where is the routing implemented in docusaurus ?

**Comment by GregBorrelly** [comment]
@hzoo  yes I'm.  I created a 404.js page, but I'm having trouble pushing.  Should I fork the repo before creating a new branch?  I apologize for the noob questions, first big open source project I contribute too.

**Comment by GregBorrelly** [comment]
https://github.com/babel/website/pull/1540
