### ISSUE TITLE
New Site: Setup/Tools page

### ISSUE THREAD

**Issue by hzoo** [babel/website#1527]
Basically the same idea as in https://github.com/babel/website/issues/1522

> This one might be a little more involved

We need to port the [setup](https://babeljs.io/docs/setup) page in the new site since the old one used jekyll (`{% for category in site.data.tools %}`) and bootstrap css

This would be targeting the [`docusaurus`](https://github.com/babel/website/tree/docusaurus) branch, not master.

> I would read through some of the docs: https://docusaurus.io/docs/en/installation.html + and check out the branch

We can probably just redo how this works? Not sure the time investment though.

---

If we port:

- [ ]  we need to basically convert the setup page - https://github.com/babel/website/blob/docusaurus/docs/setup.md and https://github.com/babel/website/blob/docusaurus/_includes/tools/items.md
- [ ] should probably move the [data](https://github.com/babel/website/blob/docusaurus/_data/tools.yml) into a different file or just in the tools.js file itself (doesn't matter to me right now). Same with https://github.com/babel/website/blob/docusaurus/_includes/tools
- [ ] will need to re-create/create styling for that page: current styling at https://github.com/babel/website/blob/docusaurus/_sass/pages/_tools.scss. Totally fine if you can improve on what's there as well so it doesn't "have" to look the same

**Comment by QC-L** [comment]
Let me try, but I didn't think about how to design it. I realized it first.

**Comment by QC-L** [comment]
@hzoo How do you feel like that?
![](http://oypz34fc0.bkt.clouddn.com/babel-setup.png)

**Comment by xtuc** [comment]
@QC-L that looks good. I'm not sure about the yellow background on the buttons. Maybe could we change it to white?

**Comment by QC-L** [comment]
White is the original effect. How do we make some changes?

**Comment by hzoo** [comment]
I think it's all good now, we'll probably want to redo this in the future anyway (a lot of the packages aren't really updated or maintained by us either)

**Comment by QC-L** [comment]
@hzoo I found that docusaurus doesn't seem to support `onClick`

**Comment by xtuc** [comment]
Ok, fine to me

> @hzoo I found that docusaurus doesn't seem to support onClick

Outch, we could maybe ask @JoelMarcey

**Comment by QC-L** [comment]
Hey, @JoelMarcey. I try to add the `onClick` event in the `<a>` tag, but didn't take effect. Is Docusaurus not supported? I searched through all the documents and found nothing.

**Comment by JoelMarcey** [comment]
@QC-L Hi! We definitely did not purposely avoid support for `onclick`. Let me look into this. Sorry.

**Comment by QC-L** [comment]
@JoelMarcey THX. Sorry for the inconvenience.

**Comment by JoelMarcey** [comment]
@QC-L Hi. No problem. Do you have a PR open or a code snippet of how and where you are trying to use `onclick`?

**Comment by QC-L** [comment]
@JoelMarcey You can see #1541 . 
```
selectItem(groupIndex, itemIndex) {
  console.log(groupIndex, " ", itemIndex);
}
```
No response.

**Comment by JoelMarcey** [comment]
@QC-L I was talking it over with another core Docusaurus team member, @rickyvetter, and he reminded me that `onclick` can't work out of the box since Docusaurus sites are server rendered. 

> the html is generated at build time through a node process as opposed to on the browser when someone loads the page. Since we are just shipping the markup output then dynamic things like click handlers won’t work. We would have to ship the whole application to the client if we wanted that.

Your best option here is probably just including a script tag in vanilla JavaScript that handles your click events (there are some other options, but they might not be as amenable).

@rickyvetter has a Docusaurus site, Reason-React, where he did something similar. https://github.com/reasonml/reason-react/blob/master/website/core/Footer.js

**Comment by QC-L** [comment]
@JoelMarcey THX! Let me try.

**Comment by QC-L** [comment]
@hzoo It's finished tomorrow morning. It's a little bit worse.

**Comment by hzoo** [comment]
K fixed by https://github.com/babel/website/pull/1541

- should remove jquery and use dom methods
- figure out what's the deal with translation
- potentially redo the setup if ^ doesn't work well

**Comment by hzoo** [comment]
K fixed by https://github.com/babel/website/pull/1541

- should remove jquery and use dom methods
- figure out what's the deal with translation
- potentially redo the setup if ^ doesn't work well

**Comment by azz** [comment]
@JoelMarcey Is there any chance this will eventually be supported by  docasaurus? https://github.com/facebook/Docusaurus/issues/292#issuecomment-357222593

**Comment by QC-L** [comment]
@hzoo I'm trying to fix them.

**Comment by JoelMarcey** [comment]
@azz Hi. Yes. This is something we are looking at supporting. I would really like if we could design it  in the constructs of our current build system. I //think// we can take some clues from some of the customizations that were done with React Native and maybe even Prettier.
