### ISSUE TITLE
New Site: Users page

### ISSUE THREAD

**Issue by hzoo** [babel/website#1528]
> Current page is at https://babeljs.io/users/
> New site is http://localhost:3000/users.html if you run locally
> https://deploy-preview-1521--babel.netlify.com/users.html from the preview in https://github.com/babel/website/pull/1521

Looks like the styles are kind of weird, so this task is to fix those to be similar to the current version. Free free to make other changes if it seems more suitable though.

This would be targeting the [`docusaurus`](https://github.com/babel/website/tree/docusaurus) branch, not master.

> I would read through some of the docs: https://docusaurus.io/docs/en/installation.html + and check out the branch

- Again check `website/pages/en/users.js` and then modify the styles in static/css/users.css (make a new file)?

**Comment by ajaymathur** [comment]
cool, can I please do it 🙂

**Comment by hzoo** [comment]
Done by https://github.com/babel/website/pull/1529
