### ISSUE TITLE
New Site: Code Blocks

### ISSUE THREAD

**Issue by SavePointSam** [babel/website#1531]
The code blocks provided by Docusaurus with the help of Highlightjs don't yet match the stylings of the old site. They need the following to match the old site:

- [x] port of Tomorrow theme
- [x] header added atop the block
- [x] language shown in header
- [ ] 'Copy' button in header
- [ ] 'Try' button in header

Updates should be PR'd into the main, new website branch #1521.

**Comment by SavePointSam** [comment]
With a bit of trickery, I was able to add the header back to the code block and added Titles for all the previously supported languages of the old site.

However, adding the Copy and Try button's back will be somewhat tricky. Currently the page is being rendered by `Docusaurus/lib/core/Remarkable.js`. We will need to find a way to create a custom header to append to this component in order to have a full-featured header like the previous site did.

I would guess the best course of action to take would be to either submit a PR or ask about how they could expose a way to us to inject an optional header component to render alongside the code block that would still have access to the source Markdown in some way so that authors will be able to easily add or remove the actions.

**Comment by hzoo** [comment]
We don't have to do things the old way but I think having the buttons are nice

**Comment by SavePointSam** [comment]
I really like the buttons as well. I'm gonna look into possibly making it a native Docusaurus solution as we don't have any control of the DOM.

**Comment by microbouji** [comment]
I think docusaurus allows us to register custom remarkable plugins from siteConfig. So we could probably write a plugin if we wanted to enable doc authors to choose the buttons they want to show up for the code blocks directly from markdown as described above.

In the meantime I sent PR #1594  that adds the buttons with frontend javscript like in the old site. The 'Copy' button is added to all code blocks and the 'Try' button to all js blocks.

**Comment by hzoo** [comment]
I guess we can close this now? Even if we want it native

**Comment by microbouji** [comment]
Yep, all seems done here
