### ISSUE TITLE
New Site: redirects

### ISSUE THREAD

**Issue by hzoo** [babel/website#1535]
We need to redirect for any changes in the url structure of the site

We already have this file: https://github.com/babel/website/blob/master/_redirects

So we just need to update it after looking at https://www.netlify.com/docs/redirects/

- so things like if we rename https://babeljs.io/learn-es2015/ to https://babeljs.io/docs/env/learn.html it should be `/learn-es2015 /docs/en/learn.html`
- the rest of the readme pages or any thing that got renamed
- docusarus is only a flat doc structure and we had nested before

EDIT: we should maybe add a section about this in the 404 page? Like if you are coming from an external URL, file an issue for us to add a redirect?

**Comment by ajaymathur** [comment]
can I take this up?

**Comment by hzoo** [comment]
Yeah although not sure you know where to look for the old urls - if so it should be really easy with a glob type thing

**Comment by ajaymathur** [comment]
From your comment- I thought old urls are at https://github.com/babel/website/blob/master/_redirects

I can update by looking at that?

**Comment by nicolo-ribaudo** [comment]
https://github.com/facebook/Docusaurus/issues/248 might make this easier.

**Comment by hzoo** [comment]
Yeah we just need to update https://github.com/babel/website/blob/master/_redirects is all. I just mean we need to make sure it works for all the previouos urls we know about (hard to know but we can add as we learn about them too)

**Comment by hzoo** [comment]
Closed by https://github.com/babel/website/pull/1567
Closes https://github.com/babel/website/pull/1561
