### ISSUE TITLE
New site: Main Page

### ISSUE THREAD

**Issue by hzoo** [babel/website#1538]
I guess we should just port what we currently have?

> but we'll also probably want to redo this page later/soon (or just move the contents into an about page)

Similar to https://github.com/babel/website/issues/1522 and https://github.com/babel/website/issues/1523

---
This would be targeting the [`docusaurus`](https://github.com/babel/website/tree/docusaurus) branch, not master.

> I would read through some of the docs: https://docusaurus.io/docs/en/installation.html + and check out the branch

- [x] Convert https://github.com/babel/website/blob/master/index.md into js and put it into https://github.com/babel/website/blob/docusaurus/website/pages/en/index.js (You can probably throw away most of what is in that file since it's just a placeholder). Remember the main site is at https://babeljs.io, the mini repl code is at https://github.com/babel/website/blob/master/scripts/index.js
- [x] old styling code might be in https://github.com/babel/website/blob/docusaurus/_sass/, can delete unused code later
- [x] if it's difficult to port I would skip the mini repl at first and we can do that in a new pr https://github.com/babel/website/pull/1564
- [x] Would like to get some of our open collective sponsors up there at least the gold sponsors like on vuejs.org https://github.com/babel/website/pull/1564

**Comment by hzoo** [comment]
Ok I just removed the old text contents and moved them into a new index/about page.

**Comment by microbouji** [comment]
Hi, I'd like to work on this.

**Comment by hzoo** [comment]
Mostly done in https://github.com/babel/website/pull/1564 so closing!
