### ISSUE TITLE
Gulp setup is out-of-date

### ISSUE THREAD

**Issue by demurgos** [babel/website#1547]
[Reported by @NiavlysB](https://github.com/babel/gulp-babel/issues/124#issuecomment-361962491).

The installation step is missing the peer dependency on `babel-core`. [See npm page](https://www.npmjs.com/package/gulp-babel).

**Comment by hzoo** [comment]
We're in the process of remaking the website via https://github.com/babel/website/issues/1485 and https://github.com/babel/website/pull/1521 due to this issue and others

**Comment by hzoo** [comment]
Oh I guess we did this in https://github.com/babel/website/pull/1555, closing!

Thanks for the reports 🙂
