### ISSUE TITLE
[new site] Code snippets not scrollable on mobile

### ISSUE THREAD

**Issue by maaz93** [babel/website#1549]
The snippets are cut off on mobile. And I'm not able to scroll them.

![smartselectimage_2018-02-02-06-55-39](https://user-images.githubusercontent.com/6594255/35712070-4a906146-07e6-11e8-9c5c-10db7764e511.png)

I'd like to fix this if that's ok. 😄

**Comment by hzoo** [comment]
Would this be a docusaurus issue or ours? fine with me!

**Comment by JoelMarcey** [comment]
I noticed on some other sites that use Docusaurus, that code snippets are wrapped or can be scrolled using touch.
