### ISSUE TITLE
Some links cutoff in the header on mobile

### ISSUE THREAD

**Issue by maaz93** [babel/website#1556]
This could be a Docusaurus bug or intentional? Not all the links in the header are visible on mobile (Notice the `GitHub` link is cutoff in the mobile screenshot).

## Mobile
![smartselectimage_2018-02-03-23-03-21](https://user-images.githubusercontent.com/6594255/35769869-e270607c-0937-11e8-8ecd-0823ac4db2ef.png)

## Desktop
![smartselectimage_2018-02-03-23-10-11](https://user-images.githubusercontent.com/6594255/35769875-febba62e-0937-11e8-826f-0185a0ab775c.png)

**Comment by JoelMarcey** [comment]
@maaz93 Hi. Are you still seeing this behavior? When I look at the site, I think I see all the links on mobile now, including the `GitHub` link which I didn't see in your pasted image above.

**Comment by maaz93** [comment]
@JoelMarcey I still see this on my mobile. The particular screenshot in the issue was taken on my mobile itself. Just to experiment and be sure that it's not because of some CSS on the babel site, I added a new `li` on the Docusaurus site. It's cut off even there

![cut_off](https://user-images.githubusercontent.com/6594255/35841621-f8f6324e-0b22-11e8-9913-2e37deee2581.PNG)

**Comment by JoelMarcey** [comment]
@maaz93 Ah! I see what you are saying. When you say "Missing", you are meaning cutoff. Is that correct? So in the original post you made above, "GitHub" was probably there, just not visible because it was cutoff.

That is definitely a Docusaurus bug. Thanks!

**Comment by maaz93** [comment]
@JoelMarcey yes! I should've used the word cutoff.

**Comment by microbouji** [comment]
#1603 should fix this too
