### ISSUE TITLE
Try it out: CodeMirror is not defined

### ISSUE THREAD

**Issue by andrzej-aa** [babel/website#1560]
I'm not sure how does it work but it looks like CodeMirror@5.30 on unpkg.com was removed and now CodeMirror@5.34 is available. Because of that the Try it out function doesn't work.

**Comment by xtuc** [comment]
Could you try to access https://unpkg.com/codemirror@5.30.0/lib/codemirror.js? It's working on my side.

**Comment by andrzej-aa** [comment]
I always get `Cannot find module "/lib/codemirror.js" in package codemirror@5.30.0`. Tried in different browsers, as well in incognito mode.

**Comment by xtuc** [comment]
Might be on unpkg's side then, cc @mjackson :innocent: ?

**Comment by mjackson** [comment]
@andrzej-aa Where are you? It might help to understand why you weren't able to load the file but we are.

**Comment by andrzej-aa** [comment]
Naha, Okinawa, Japan. I'm traveling around Japan for a few months and it happened a few times that CodeMirror couldn't be loaded on the Try it out page. But usually it works.

I checked the link on my phone. Surprisingly CodeMirror@5.30 works when I'm using mobile data. The problem still occurs on my computer.

**Comment by mjackson** [comment]
Sounds like there's a bad file in your ISP's cache. I've cleared the unpkg cache for https://unpkg.com/codemirror@5.30.0/lib/codemirror.js so hopefully that should clear it up.

**Comment by andrzej-aa** [comment]
Today I moved to a new location. My ISP also changed and https://unpkg.com/codemirror@5.30.0/lib/codemirror.js started working. But, now I get 404s on other resources like https://unpkg.com/codemirror@5.30.0/keymap/sublime.js so url https://babeljs.io/repl/ still doesn't work. This is how it looks in the resources panel: http://prntscr.com/ibqlaj

**Comment by andrzej-aa** [comment]
Currently [https version](https://babeljs.io/repl/) of the feature returns 404. Was it the case and you decided to turn it off? Right now the Try it out feature works only under http://babeljs.io/repl/ Or maybe it's because I'm in Taiwan?

**Comment by xtuc** [comment]
Works on my side (EU).

**Comment by andrzej-aa** [comment]
Okay, false alarm. It works again. Probably some long update in progress (?)

**Comment by xtuc** [comment]
Can we close this issue btw?

**Comment by andrzej-aa** [comment]
The problem occurred when I was in Japan. I'm going back there in a few weeks, but we can close it as for now. I think I can reopen it in case it happens again.

**Comment by existentialism** [comment]
@andrzej-aa thanks
