### ISSUE TITLE
babel-polyfill links in Caveats landing on 404 page

### ISSUE THREAD

**Issue by maaz93** [babel/website#1563]
The 2 links which point to `babel-polyfill` on the [Caveats page](https://new.babeljs.io/docs/en/caveats.html) point to "https://new.babeljs.io/docs/en/babel-polyfill.md" rather than "https://new.babeljs.io/docs/en/babel-polyfill.html". This results in landing to 404 page when clicked.

**Comment by hzoo** [comment]
Thanks for reporting.. I think it's because the filename is `polyfill` still hm
