### ISSUE TITLE
confusing package name in docs

### ISSUE THREAD

**Issue by khubo** [babel/website#1566]
https://babeljs.io/blog/2017/03/01/upgrade-to-babel-7#babel-node

According to this link `babel-node` is suppose to be installed sepreate as its made a seprate package from babel-cli 7 ownwards. As there is already a package named babel-node which is not the required one documentation is kind of confusing here. 

p.s :- love what you guys are doing 👍 . thanks for the awesome tool 💃

**Comment by hzoo** [comment]
Ah yeah we need to update all those docs. I might just move them out of the blog (we are using scoped packages now so it would be `@babel/node` to answer your question! 😄

**Comment by khubo** [comment]
@hzoo  omg, that was quick 😂 . You are a robot 🙆‍ . thank you 💃

**Comment by hzoo** [comment]
Alright so we already updated that in the new site! http://new.babeljs.io/docs/en/next/v7-migration.html#babel-node

But maybe we want to link to that new page from the current version? Ok I just did that as well here: https://babeljs.io/blog/2017/03/01/upgrade-to-babel-7!

Thank you! 🎉
