### ISSUE TITLE
New Site: link from old to new site

### ISSUE THREAD

**Issue by hzoo** [babel/website#1571]
I think we should also have a banner on the current/old site (branch `old-site`) to tell people we are working on the new one and to give feedback.

So add a link that points to `new.babeljs.io`

And when we switch and people get linked to old urls, they will know that we have more updated docs on the new site. (kind of like how webpack had a banner before from the github.io site to the new webpack.js.org site)

**Comment by AkshatSrivastava2** [comment]
@hzoo Are we still up with this issue? I can work with this.

**Comment by hzoo** [comment]
I moved babeljs.io to be the new site so this isn't an issue anymore!
