### ISSUE TITLE
Broken link to env preset page from the ES2015 preset page

### ISSUE THREAD

**Issue by hidace** [babel/website#1583]
Noticed that [the link to the env preset](https://babeljs.io/docs/plugins/preset-es2015/) from the section titled **Basic Setup (with the CLI)** under 'Run it' goes to a [404 page](https://babeljs.io/docs/en/babel-preset-env) . I believe it should go to [here](https://babeljs.io/docs/plugins/preset-env/)

**Comment by xtuc** [comment]
Good catch. Do you mind sending us a PR?

**Comment by Akiyamka** [comment]
@hidace, thanks for the correct link! I found a similar problem is observed here too.
https://babeljs.io/docs/usage/api/#options have [broken links](https://babeljs.io/docs/en/plugins#presets) in presets and plugin. 
`List of presets (a set of plugins) to load and use.`
`List of plugins to load and use.`

**Comment by Akiyamka** [comment]
Another [broken link](https://babeljs.io/docs/en/babel-preset-env) on [this page](https://babeljs.io/docs/plugins/preset-es2015/#top)
`This is deprecated. If you want to stay up to date, use the env preset`

**Comment by ashleytqy** [comment]
This relates to https://github.com/babel/website/issues/1592 (another broken link)
I can help to update the broken links if it's not already been worked on :-)

**Comment by existentialism** [comment]
Should be fixed by https://github.com/babel/website/commit/cc0db1003319fbd4973bd6919fd22579936bc894
