### ISSUE TITLE
stage-x articles broken links and confusion

### ISSUE THREAD

**Issue by malydok** [babel/website#1589]
(Old docs) All of the stage-x articles contain duplicate sections with `This preset includes the following plugins` and `And all plugins from presets` link lists. The second area, beneath "stage gist", always contains broken links.
E.g. https://babeljs.io/docs/plugins/preset-stage-0/

The broken links consist of `docs/en/babel-preset-stage-x`, which seems to be the structure of the new docs, and may be leaking into the old one.

I've tried looking at the markup of the articles but none of them contain the sections in question (https://github.com/babel/babel/blob/master/packages/babel-preset-stage-0/), and the mechanism for their inclusion eludes me.

**Comment by existentialism** [comment]
Should be fixed in 86d9b9bd5d6ad2c2942fd488053e2185cb874d42
