### ISSUE TITLE
Page not found : https://babeljs.io/docs/en/babel-polyfill

### ISSUE THREAD

**Issue by thesimpledesigners** [babel/website#1592]
404
Page not found. 
when trying to access the babel-polyfill page from the following doc :
https://babeljs.io/docs/usage/babel-register/

**Comment by ashleytqy** [comment]
Hi! I think the correct link is https://babeljs.io/docs/usage/polyfill/

Shall I make a PR to fix this broken link?

**Comment by xtuc** [comment]
> Shall I make a PR to fix this broken link?

That would be great, thanks!

**Comment by existentialism** [comment]
Should be fixed by https://github.com/babel/website/commit/cc0db1003319fbd4973bd6919fd22579936bc894

**Comment by hzoo** [comment]
Sorry about that, it should work now!

I updated the old website (the current one) to use the new urls. Now it should redirect correctly. https://github.com/babel/website/commit/cc0db1003319fbd4973bd6919fd22579936bc894

**Comment by thesimpledesigners** [comment]
Thanks
