### ISSUE TITLE
"Only official Plugins" checkbox is toggled when clicking in plugin name field in Safari

### ISSUE THREAD

**Issue by eventualbuddha** [babel/website#1610]
![babel-website-bug](https://user-images.githubusercontent.com/1938/38036118-db4e0c94-325a-11e8-886a-98c5241add0f.gif)

### Steps to Reproduce

1. Go to the [repl](https://babeljs.io/repl/) in Safari on macOS.
2. Toggle open the "Plugins" section.
3. Click on the field with placeholder "Type the plugin name".

### Expected

The field should receive input focus.

### Actual

The field briefly receives input focus but the "Only official Plugins" checkbox toggles its state and the plugin name field loses input focus, making it impossible to focus with the mouse. It can still be focused with the keyboard.

### Commentary

This is likely due to the weird HTML structure of this section of the sidebar. The plugin name `<input>` is inside a `<label>` which also contains another `<label>` which contains the checkbox `<input>`. I think this structure may not be valid, which means that behavior may be somewhat undefined.

```html
<label class="css-1ialo1l">
    <div class="css-13l6cwb">
        <label class="css-1h259tg css-1xo3mso">
            <input type="checkbox" class="css-1yr5jo5" value="on" />Only official Plugins
        </label>
        <input
                type="text"
                placeholder="Type the plugin name"
                value=""
                class="css-1qjy9c4 css-qnx592"
        />
        <div class="ais-Hits__root">
            <label class="css-13o7eu2">
                <input type="checkbox" class="css-1yr5jo5" value="on" />transform-es2015-modules-commonjs
            </label>
            <label class="css-13o7eu2">
                <input type="checkbox" class="css-1yr5jo5" value="on" />transform-strict-mode
            </label>
            <label class="css-13o7eu2">
                <input type="checkbox" class="css-1yr5jo5" value="on" />transform-regenerator
            </label>
            <label class="css-13o7eu2">
                <input type="checkbox" class="css-1yr5jo5" value="on" />transform-es2015-parameters
            </label>
            <label class="css-13o7eu2">
                <input type="checkbox" class="css-1yr5jo5" value="on" />transform-es2015-block-scoping
            </label>
            <label class="css-13o7eu2">
                <input type="checkbox" class="css-1yr5jo5" value="on" />transform-es2015-destructuring
            </label>
            <label class="css-13o7eu2">
                <input type="checkbox" class="css-1yr5jo5" value="on" />transform-es2015-function-name
            </label>
            <label class="css-13o7eu2">
                <input type="checkbox" class="css-1yr5jo5" value="on" />transform-es2015-unicode-regex
            </label>
            <label class="css-13o7eu2">
                <input type="checkbox" class="css-1yr5jo5" value="on" />transform-es2015-sticky-regex
            </label>
            <label class="css-13o7eu2">
                <input type="checkbox" class="css-1yr5jo5" value="on" />transform-es2015-spread
            </label>
        </div>
    </div>
    <div />
</label>
```

**Comment by xtuc** [comment]
That's a funny one! @Haroenv also had this bug https://github.com/babel/website/pull/1518#issuecomment-363089992.

Would you mind sending a PR?

**Comment by eventualbuddha** [comment]
Yep, looks like @Haroenv pointed this out in the original PR. I don't have time at the moment to send a PR, and likely won't as this isn't a high priority issue for me. I just wanted to make sure it's documented.

**Comment by Haroenv** [comment]
My suspicion is that this comes from some id clashing or shared label, but didn't exactly find a workaround easily.
