### ISSUE TITLE
Issue with markdown headings

### ISSUE THREAD

**Issue by hzoo** [babel/website#1614]
http://new.babeljs.io/docs/en/next/v7-migration.html

![image](https://user-images.githubusercontent.com/588473/38152749-22c083d0-3437-11e8-8f86-25cb7f8acfec.png)

**Comment by microbouji** [comment]
I'll send a fix to docusaurus tomorrow.

**Comment by hzoo** [comment]
Yep all good whenever, just wanted to ping

**Comment by microbouji** [comment]
@JoelMarcey thanks that will be nice to have in a release before switching over. I believe we also have some new v7 docs to write that will take some more time.
