### ISSUE TITLE
Docs for Babel 7 breaking change to presets

### ISSUE THREAD

**Issue by alexparish** [babel/website#1621]
The guide on upgrading to Babel 7 (https://babeljs.io/blog/2017/03/01/upgrade-to-babel-7) should state that babel presets now need to export a function rather than an object, along with the reasoning behind this change.

This will help ease the migration for people who author their own presets. 

Currently the only clue that the API has changed is the following error:

"Module build failed: Error: Plugin/Preset files are not allowed to export objects, only functions."

**Comment by hzoo** [comment]
So we removed the blog posts in the new site and I made http://new.babeljs.io/docs/en/next/v7-migration.html instead.

https://github.com/babel/website/blob/master/docs/v7-migration.md

I'll add that though, thanks
