### ISSUE TITLE
missing @babel/plugin-proposal-class-properties in @babel/preset-stage-3

### ISSUE THREAD

**Issue by ncaq** [babel/website#1639]
I see [babel-preset-stage-3 · Babel](https://new.babeljs.io/docs/en/next/babel-preset-stage-3.html)

proposal-class-properties do not exist in document.

However, @babel/preset-stage-3 depend proposal-class-properties.

I know babel 7 include and babel 6 not include.

However, I see next document. Is it babel 7 document?

**Comment by microbouji** [comment]
Yes, the pages under /next are for babel 7. Many package readmes though (including babel-preset-stage-3) are, for the moment, automatically downloaded to this repo from the main babel repo.

The original document for that page is this: https://github.com/babel/babel/blob/master/packages/babel-preset-stage-3/README.md

You might want to send a PR there to add a note for proposal-class-properties.

**Comment by hzoo** [comment]
I don't think we are planning to document each stage in the the site? https://babeljs.io/docs/en/next/babel-preset-stage-3.html I would just link to the repo or the stage process in https://github.com/tc39/proposals
