### ISSUE TITLE
Docs don't included latest plugins - plugin-transform-unicode-regex

### ISSUE THREAD

**Issue by leimonio** [babel/website#1644]
When visiting https://babeljs.io/docs/plugins/ I can see a list of plugins, and the pages of the plugins seems outdated. 

More specifically [es2015-unicode-regex](https://babeljs.io/docs/plugins/transform-es2015-unicode-regex/) has references to [babel-plugin-transform-es2015-unicode-regex instead](https://www.npmjs.com/package/babel-plugin-transform-es2015-unicode-regex) instead of [@babel/plugin-transform-unicode-regex](https://www.npmjs.com/package/@babel/plugin-transform-unicode-regex)

**Comment by existentialism** [comment]
@leimonio the babeljs.io docs represent 6.x docs, we are in the process of gettin v7 docs done in time for its release and get version switching between them (you can preview this work at new.babeljs.io), thanks!

**Comment by leimonio** [comment]
@existentialism Great, thanks for sharing! 👍
Please let me know if you are searching for any contributors!
