### ISSUE TITLE
In `Planning for 7.0` blog post, strikethrough section about env deprecation

### ISSUE THREAD

**Issue by vjpr** [babel/website#1646]
This post still comes up in search results for `babel 7 feature` and more.

https://github.com/babel/website/blob/master/website/blog/2017-09-12-planning-for-7.0.md#deprecate-the-env-option-in-babelrc

https://github.com/babel/babel/issues/5276#issuecomment-348598859:

> We've decided that this isn't necessary because we've changed how Babel 7 handles option merging to make this more reasonable for users, and that should be enough.

https://github.com/babel/website/blob/master/website/blog/2017-12-27-nearing-the-7.0-release.md#the-env-option-in-babelrc-is-not-being-deprecated

**Comment by hzoo** [comment]
It does say `## 💀 Possible Deprecations` but good suggestion!

**Comment by hzoo** [comment]
https://github.com/babel/website/commit/d51f3aba4cd8d9476de82c35340e1cd37edd2cba
