### ISSUE TITLE
Include file extension in REPL config options

### ISSUE THREAD

**Issue by loganfsmyth** [babel/website#1666]
With https://github.com/babel/babel/pull/7955 Babel now allows both the flow and typescript presets to be used in parallel, and allows JSX only in `.tsx`, not `.ts` files. Given that, we'll want to stop hard-coding the filename "repl" with no extension in https://github.com/babel/website/blob/71a346f6ab95047b9c6a1df373aca5b9dc609501/js/repl/compile.js#L84

Including the extension is important now, so the UI should expose that as well.

**Comment by AkshatSrivastava2** [comment]
@loganfsmyth I am a first-time contributor. I want to work on this issue.

**Comment by loganfsmyth** [comment]
@AkshatSrivastava2 Go for it! Feel free to join our Slack if you want to chat and ask us questions about it. We have a channel for the website on there.

**Comment by alexzherdev** [comment]
@AkshatSrivastava2 @loganfsmyth I can help get this to the finish line.
