### ISSUE TITLE
Include sourceType in REPL config options

### ISSUE THREAD

**Issue by loganfsmyth** [babel/website#1667]
Along the same lines as #1666, Babel transforms can vary in behavior depending on the `sourceType`, so it would be good to expose that option in the REPL.

**Comment by alexzherdev** [comment]
I'd like to work on this if it makes sense to get this started while #1666 is being worked on. (I could solve conflicts later if there are any)

**Comment by loganfsmyth** [comment]
@alexzherdev Go for it. If you're not familiar, there are 3 types of `sourceType` that we'd want, `unambiguous`, `script`, and `module`.

**Comment by alexzherdev** [comment]
This is coming along nicely, will be ready shortly. Here's what it looks like currently, let me know if you were invisioning something else @loganfsmyth 
<img width="232" alt="screen shot 2018-06-01 at 9 31 02 am" src="https://user-images.githubusercontent.com/93752/40852234-a31979ce-657e-11e8-909e-0dadcdf819a7.png">

**Comment by nicolo-ribaudo** [comment]
Maybe you could add some left padding to align it with the other labels?

**Comment by alexzherdev** [comment]
Actually, there's not quite enough space to do that (I'd have to shrink the dropdown too which didn't look nice), so I ended up not changing it

**Comment by alexzherdev** [comment]
Good to close now @existentialism @loganfsmyth ?

**Comment by existentialism** [comment]
@alexzherdev yep thanks!
