### ISSUE TITLE
Wrong out in some examples of a preset-env plugin.

### ISSUE THREAD

**Issue by NMVikings** [babel/website#1670]
https://babeljs.io/docs/plugins/preset-env/

Config:

```
{
  "presets": [
    ["env", {
      "targets": {
        "chrome": 52
      }
    }]
  ]
}
```

Out for `Target only Chrome 52` on website:

```
class A {}
exports.A = A;
```

Out on [REPL](https://babeljs.io/repl/#?babili=false&browsers=chrome%2052&build=&builtIns=false&code_lz=KYDwDg9gTgLgBAYwDYEMDOa4EE4G8C-AUEA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&lineWrap=true&presets=env&prettier=false&targets=&version=6.26.0&envVersion=1.6.2) with same config:

```
"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
class A {}
exports.A = A;
```

Did i miss something or there are some mistakes in docs?

**Comment by hzoo** [comment]
Yeah I guess I just didn't include that extra part above is all, didn't want to make the example that large.
