### ISSUE TITLE
Link to "Learn ES2015" is broken

### ISSUE THREAD

**Issue by DavidEspinola** [babel/website#1692]
The link "Learn ES2015" (https://babeljs.io/docs/en/learn.html) at the footer is broken and results in a 404. I can't find that page in this repo, but you may link it to the old website https://old.babeljs.io/learn-es2015/

**Comment by hzoo** [comment]
Thanks for the report! Yea the link is missing `/en`. https://github.com/babel/website/commit/819c0cc9e319fec7ab5893870651493cc9eafc30
