### ISSUE TITLE
Document new --config-file option

### ISSUE THREAD

**Issue by xtuc** [babel/website#1709]
Since https://github.com/babel/babel/pull/6133 we are now able to specify the location of the Babel configuration in the CLI.

Would be great if someone actually document it!

**Comment by mgred** [comment]
This seems to be documented already (at least in the new docs): https://github.com/babel/website/commit/44148313f47312164715b03ffe2e438c1790312f#diff-f25cc7613a9dc426e5a6fb653c139200R222

**Comment by hzoo** [comment]
https://babeljs.io/docs/en/options#configfile
