### ISSUE TITLE
babel-preset-es20XX deprecation warning has link without protocol in it

### ISSUE THREAD

**Issue by jplatte** [babel/website#1710]
Just created a new project based on an older one where I used babel-preset-es201{5,6} and I noticed that the deprecation message for those two doesn't contain `https://`. The Visual Studio Code terminal thus didn't recognize it as a link and I couldn't Ctrl+Click it, and also when I pasted the link into my browser the page loaded via http, no redirect to https (see #804).

It would be nice if the link in the deprecation message was updated from `babeljs.io/env` to either `https://babeljs.io/env` or `https://babeljs.io/docs/en/env/` (which the former redirects to).

**Comment by jplatte** [comment]
Oops, just noticed the repo. I was originally going to open an issue for no http -> https redirect but since that already exists just changed the issue content. I can't find a repo for the old presets on your GitHub org though, so I won't close yet.

**Comment by danez** [comment]
I updated the deprecation notice.
