### ISSUE TITLE
`babylon` link is broken

### ISSUE THREAD

**Issue by yanivefraim** [babel/website#1716]
There is a 404 page when trying to go to `tooling/babylon`,

**Comment by hzoo** [comment]
Can you say where you clicked it from? This is because we changed to `@babel/parser` as a rename

**Comment by nicolo-ribaudo** [comment]
I think that we should both change the link and have the redirect, since external sites still point to Babylon.

**Comment by yanivefraim** [comment]
Sure, I clicked it from `https://babeljs.io/docs/en` (see screenshot attached). Thanks!

![screen shot 2018-07-08 at 13 30 45](https://user-images.githubusercontent.com/1336186/42418928-758b6bf0-82b3-11e8-94b5-83cbc2d069bc.png)

**Comment by codeudan** [comment]
Url "https://babeljs.io/docs/en/api.md" is broken (Response 404 page) too. This link from "Options" in https://babeljs.io/docs/en/babelrc.
