### ISSUE TITLE
Click on Edit leads to 404

### ISSUE THREAD

**Issue by hexagon6** [babel/website#1730]
Context:

I saw 2 dead links in the following page:

https://babeljs.io/docs/en/babel-plugin-transform-object-rest-spread

thus, I wanted to fix it, so I clicked on `Edit` which leads me to https://github.com/babel/website/blob/master/docs/plugin-transform-object-rest-spread.md which is not there anymore.

How to fix this? I would like to volunteer.

**Comment by hzoo** [comment]
Closed by https://github.com/babel/website/pull/1731
