### ISSUE TITLE
Better page for babel's options

### ISSUE THREAD

**Issue by Andarist** [babel/website#1755]
At the moment this - http://babeljs.io/docs/en/next/babel-core#options is hard to link to. @loganfsmyth has suggested also the table is hard to read, it's fine for me though.

Not sure how exactly algolia plugin works, but it doesn't index this so in example phrase "babelrcRoots" cannot be found with the search, maybe that's the table's fault?

**Comment by hzoo** [comment]
Yeah we can just remove the table and make headings

**Comment by loganfsmyth** [comment]
I don't think the options should be under `babel-core` either because no-one thinks to look there because they think of Babel as one overall unit. It would be better to have a top-level documentation page for the options, I think.

**Comment by hzoo** [comment]
Ok Logan did an amazing job at this in https://babeljs.io/docs/en/options
