### ISSUE TITLE
let+const+module 

### ISSUE THREAD

**Issue by Sinkyears** [babel/website#1763]
The following code does not compile
let+const 

function f() {
  {
    let x;
    {
      // this is ok since it's a block scoped name
      const x = "sneaky";
      // error, was just defined with `const` above
      x = "foo";
    }
    // this is ok since it was declared with `let`
    x = "bar";
    // error, already declared above in this block
    let x = "inner";
  }
}

**Comment by xtuc** [comment]
@babel-bot move babel/babel

**Comment by xtuc** [comment]
@babel-bot move to babel/babel

**Comment by xtuc** [comment]
Our bot seems not moving your issue. Could you please open a new issue on https://github.com/babel/babel and use our issue template.
