### ISSUE TITLE
Add some more Babel talks!

### ISSUE THREAD

**Issue by hzoo** [babel/website#1767]
To https://github.com/babel/website/blob/master/website/data/videos.yml

Any others?

- https://www.youtube.com/watch?v=XvTsxa9i13o
- https://www.youtube.com/watch?v=9sPDcVYX3g8
- https://www.youtube.com/watch?v=h0sfFX7WH1c

**Comment by xtuc** [comment]
I did:
- https://www.youtube.com/watch?v=5vnmvXuwzJ0
- https://www.youtube.com/watch?v=hOghLCWohuU

but feel free to not include them.

**Comment by btholt** [comment]
I have one! https://www.youtube.com/watch?v=SSymzmnk0ZA&t=47s

**Comment by thiagoarrais** [comment]
Is this still up for grabs?
