### ISSUE TITLE
Change sidebar labels in latest docs

### ISSUE THREAD

**Issue by notlmn** [babel/website#1771]
- From https://github.com/babel/website/pull/1770#issuecomment-415969770
- Blocked by https://github.com/facebook/Docusaurus/issues/916
- Wait until https://github.com/facebook/Docusaurus/pull/917 gets merged or https://github.com/facebook/Docusaurus/issues/916 gets fixed somehow

I'd like to assign myself to this issue!

**Comment by hzoo** [comment]
Nice work @notImn!
