### ISSUE TITLE
Every REPL refresh downgrades the Babel version

### ISSUE THREAD

**Issue by mgol** [babel/website#1793]
Here's what I did today:

1. I opened https://babeljs.io/repl and saw version 6.something.something specified at the bottom of the page.
1. I saw #1792, opened https://babeljs.io/repl/build/master and saw Babel 7 is used.
1. Then I opened https://babeljs.io/repl again and noticed it's now on `7.0.0-rc.4`.
1. Here's when it gets funny. After every page refresh or manual navigation to https://babeljs.io/repl the Babel version used got downgraded to the previous one. The first refresh left me at `7.0.0-rc.3`, then `7.0.0-rc.2`... After `7.0.0-rc.0` it went to betas, still going down (currently it's at `v7.0.0-beta.50`).

**Comment by hzoo** [comment]
Yeah I think we should not save/cache the version then, it's just confusing
