### ISSUE TITLE
[Feature proposal] Add filtering to Who's Using page

### ISSUE THREAD

**Issue by ymschaap** [babel/website#1826]
## 💥 Proposal

The current [Who's Using](https://babeljs.io/en/users.html) page is now a huge list of 200+ company logo's. I think this could be improved upon to become more valuable.

I propose to add more details for each users in the [backend](/website/data/users.yml):
* company size
* flag sponsor or contributor
* how babel is used (link to a blog post?)
* type of user (corporate, educational, government)
* location, market (whatever might be relevant).

The frontend can then add a search and filter to surface the relevant companies that for example also contributed to the Babel ecosystem.

I made a quick mockup (note, I'm no designer):
![a quick mockup](https://user-images.githubusercontent.com/91795/45543027-d3141c00-b813-11e8-9e7f-3ccb0be09e50.png)

I also looked into Docusaurus and feel confident that I could also work on this.

Would this be a nice new feature to the website?

**Comment by xtuc** [comment]
Wow that's super cool! Do you want to work on this? Would you mind sending a PR?

**Comment by ymschaap** [comment]
Yes, would we happy to work on this.

**Comment by xtuc** [comment]
Good news! I would recommend you to join our Slack (website channel) for any question/help.

**Comment by JoelMarcey** [comment]
Sweet - is this something you could upstream to the Docusaurus core?

**Comment by ymschaap** [comment]
@JoelMarcey Yes! But makes sense to start with Babel first because of its large amount of users.

**Comment by ymschaap** [comment]
My latest updates are available here:
#1834

cc @JoelMarcey @xtuc

**Comment by ymschaap** [comment]
Closing this for PR #1834
