### ISSUE TITLE
Search for 'babel-plugin-plugin-proposal-export-default-from'

### ISSUE THREAD

**Issue by laurage** [babel/website#1832]
# Bug Report
**Current Behavior**
Console error: 
"Uncaught Error: Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Cannot find module 'babel-**plugin-plugin**-proposal-export-default-from' from '../project/path'"

**Expected behavior/code**
Module searched is  'babel-**plugin**-proposal-export-default-from'.
babel-plugin-proposal-export-default-from doesn't throw.

**Code** (following https://www.npmjs.com/package/babel-plugin-transform-export-default)
_Package.json_
```
"devDependencies": {
  "@babel/core": "^7.0.0",
  "@babel/plugin-proposal-export-default-from": "^7.0.0",
}
```

_.babelrc_
```
{
  "plugins": [
    "transform-export-default"
  ]
}
```

_index.js of MyComponent_
```
export default from './MyComponent';
```

**Comment by hzoo** [comment]
I would ask support questions on our https://slack.babeljs.io, or report bugs on https://github.com/babel/babel/. This is the website repo.

But if you are trying to use babel 7, and the dependency is `@babel/plugin-proposal-export-default-from`

I would change your config:

```js
{
  "plugins": [
    "proposal-export-default-from",
// or easier just do the whole name "@babel/plugin-proposal-export-default-from"
  ]
}
```
