### ISSUE TITLE
7.1.0 released, but docs are still on 7.0.0

### ISSUE THREAD

**Issue by dylang** [babel/website#1839]
Hi! I think either the web site hasn't been getting updated, or there's some confusion about the word "released".

|<img width="550" alt="screen shot 2018-09-23 at 12 23 57 pm" src="https://user-images.githubusercontent.com/51505/45930238-a3f45d80-bf2b-11e8-99ac-7cde657baf17.png">|
|---|
|Blog post says 7.1.0 "released", yay, `rootMode` option!|

But, hmm...

|<img width="591" alt="screen shot 2018-09-23 at 12 25 38 pm" src="https://user-images.githubusercontent.com/51505/45930269-1107f300-bf2c-11e8-980e-f9129be08294.png">|
|---|
|https://babeljs.io/versions says only 7.0.0 released and anything else is a pre-release.|

Thanks for the great work!

**Comment by existentialism** [comment]
https://github.com/babel/website/pull/1838 will fix this.
