### ISSUE TITLE
Site styling (plugins) broken on desktop

### ISSUE THREAD

**Issue by josefaidt** [babel/website#1843]
Noticed this morning the site's documentation for individual plugins seems to be broken. Does not follow same style as documentation pages. Is the sidebar supposed to collapse like this when viewing individual  plugins? If so, can this be horizontally centered?

![image](https://user-images.githubusercontent.com/5033303/46085457-b5c44380-c16b-11e8-8e9f-5f66c1af9de6.png)

**Comment by hzoo** [comment]
Yeah, I think this is because it's not part of a sidebar. And yes I think it looks really weird too, cc @JoelMarcey? I would also suggest that it would be centered if there is no left-sidebar?

**Comment by JoelMarcey** [comment]
cc @endiliey @yangshun

Looks like https://babeljs.io/docs/en/babel-node#usage is missing the left sidebar

**Comment by endiliey** [comment]
I didn't see it on the sidebars.json as well
https://github.com/babel/website/blob/master/website/versioned_sidebars/version-7.0.0-sidebars.json

**Comment by hzoo** [comment]
Yeah I guess my point is that if it's not on the sidebars.json (either intentionally or accident, as maybe there's too many to fit in the sidebar) that Docusaurus would fallback to centering it?

**Comment by microbouji** [comment]
Don't remember what version of docusaurus fixed this, but it's now centered.  Feel free to reopen if this was not just about centering.
