### ISSUE TITLE
Horizontal scroll on mobile for long `.hljs-string`

### ISSUE THREAD

**Issue by josejbreijo** [babel/website#1850]
Reading on my phone [Zero-config code transformation with babel-plugin-macros](https://babeljs.io/blog/2017/09/11/zero-config-with-babel-macros#introducing-babel-plugin-macros-https-githubcom-kentcdodds-babel-plugin-macros) saw that the page didn't fill the viewport in the right way, thus, horizontal scroll. 

According to the devtools, `overflow-x: visible;` on the `<code>` snippet element cause this issue: https://github.com/babel/website/blob/master/website/static/css/code-blocks.css#L9.

I guess that not overriding this rule and letting it use `auto` instead will solve the problem 👍.

![img_0148](https://user-images.githubusercontent.com/6707780/46330720-0b6c7600-c5da-11e8-9468-22e725da2d22.PNG)

**Comment by nicolo-ribaudo** [comment]
Do you want to open a PR and test if it works?
