### ISSUE TITLE
REPL not working - traverse.clearCache is not a function

### ISSUE THREAD

**Issue by suchipi** [babel/website#1868]
The repl is not working- when the code is compiled, no output is shown on the right, and the bottom shows "traverse.clearCache is not a function":

![](https://puu.sh/BINCW/cb9eaedcec.png)

[Link](https://babeljs.io/repl#?babili=true&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=MYGwhgzhAEBiD29oFMAeAXZA7AJjAQmAE7QDeAUNNOQL4Dc5QA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=es2015%2Cbabili&prettier=false&targets=&version=7.0.0-beta.53&envVersion=7.0.0-beta.52)

The compiled code is shown briefly when the page is first loaded, but disappears shortly.

I tested in incognito mode and have done a hard refresh.

**Comment by hzoo** [comment]
Hmm I assume it's different versions of Babel.. actually it's porbably the `minify` - maybe it's an old version of babili (should be babel-minify now) https://github.com/babel/website/issues/1311, https://github.com/babel/website/pull/1744

**Comment by suchipi** [comment]
Yeah looks like it's minify; unchecking it makes that work again.

**Comment by jakub-g** [comment]
FWIW it's still broken (unchecking `minify` fixes the issue though)

**Comment by jakub-g** [comment]
FWIW it's still broken (unchecking minify fixes the issue though)

Maybe as a quick fix the plugin should be removed from REPL until the issue is fixed properly?
Looks like removing those lines should do the trick: https://github.com/babel/website/blob/master/js/repl/PluginConfig.js#L75-L80

**Comment by JessicaSachs** [comment]
Still happening :-(

**Comment by nicolo-ribaudo** [comment]
@jakub-g Given that it's just broken and that no one is currently maintaining `@babel/minify`, I'd gladly accept a PR to remove the option.
