### ISSUE TITLE
why does babel-preset-env modules option have commonjs and cjs

### ISSUE THREAD

**Issue by monkindey** [babel/website#1886]
hi, I am confused by the `cjs` modules option in https://github.com/babel/website/blob/master/docs/preset-env.md. And I saw the [source](https://github.com/babel/babel/blob/master/packages/babel-preset-env/src/module-transformations.js#L5), is it same with `commonjs` ?

**Comment by nicolo-ribaudo** [comment]
Yeah, it's an alias.

**Comment by monkindey** [comment]
Can we clarify it in the doc?

**Comment by existentialism** [comment]
@monkindey happy to take a PR that helps clarify this, and for ref, this is the PR where it was added:

https://github.com/babel/babel/pull/7283

**Comment by monkindey** [comment]
@existentialism Thanks! Land in https://github.com/babel/website/pull/1888
