### ISSUE TITLE
`transform` is not an asynchronous function ?

### ISSUE THREAD

**Issue by joe223** [babel/website#1889]
In https://github.com/DefinitelyTyped/DefinitelyTyped/blob/9039892f8ea3823b0a37d2b9764ba413a9eb6aa9/types/babel__core/index.d.ts#L302

We can see:
```typescript
export function transform(code: string, opts?: TransformOptions): BabelFileResult | null;
```
But, documentation said that `transform` is asynchronous :
https://github.com/babel/website/blob/master/docs/core.md

```javascript
babel.transform(code, options, function(err, result) {
  result; // => { code, map, ast }
});
```
Testing with my code，**`transform` is not an asynchronous function**.

Some information would be helpful:
```json
{
  "name": "@babel/core",
  "version": "7.1.5"
}
```

**Comment by nicolo-ribaudo** [comment]
It should be used as an async function, but it can be used synchronously for backward compatibility. If you want a sync function, you should use `transformSync`

**Comment by joe223** [comment]
So, It is necessary to update types declare file  [index.d.ts](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/9039892f8ea3823b0a37d2b9764ba413a9eb6aa9/types/babel__core/index.d.ts#L302) .

**Comment by nicolo-ribaudo** [comment]
Yes, but that typings aren't maintained by us :slightly_smiling_face: 
Maybe you could open a PR? :pray:

**Comment by xtuc** [comment]
Since we don't maintain TypeScript, there's nothing actionable here I guess.
