### ISSUE TITLE
Website doesnt have updated docs for CLI

### ISSUE THREAD

**Issue by framerate** [babel/website#1897]
Just hit a major problem trying to setup a new project with Babel 7

github:

![image](https://user-images.githubusercontent.com/74291/48666216-6d8e1700-ea72-11e8-8ed2-10f51acda011.png)

Website:

![image](https://user-images.githubusercontent.com/74291/48666219-7b439c80-ea72-11e8-9bc1-47eff9d4d42b.png)

https://babeljs.io/setup#installation

The website is making users install babel-cli @6 which will break, obviously. I went to do a PR and saw this repo is already updated!

**Comment by microbouji** [comment]
This was fixed in https://github.com/babel/website/pull/1930
