### ISSUE TITLE
REPL still on 6.26.0

### ISSUE THREAD

**Issue by ricardobeat** [babel/website#1901]
The 'Try it out' link takes you to https://babeljs.io/repl which is still at v6.26; most recent plugins require v7 (ex optional chaining).

https://babeljs.io/repl/build/master/ is already at 7.1.6.

**Comment by mixtur** [comment]
This link worked for me. https://babeljs.io/repl#?version=7.2.2

Though it would be nice if I could switch between babel versions in repl.

**Comment by nicolo-ribaudo** [comment]
Try to delete the cache/cookies.

**Comment by creeperyang** [comment]
@nicolo-ribaudo it works. 

However the `https://babeljs.io/repl` still broken now. And it seems that `unpkg ` will response `404` for the url `https://unpkg.com/@babel/standalone@7.2.0/index.js`.

**Comment by nicolo-ribaudo** [comment]
Thank you for investigating; it is a publishing problem probably. I will fix it in a few days.

**Comment by nicolo-ribaudo** [comment]
@creeperyang That url seems to be working now, could you test it? Also, it should be `https://unpkg.com/@babel/standalone@7.2.0/babel.js` and not `https://unpkg.com/@babel/standalone@7.2.0/index.js`.

**Comment by nicolo-ribaudo** [comment]
`index.js` never existed.

**Comment by fiddlerwoaroof** [comment]
https://babeljs.io/repl still 404s for me.

**Comment by fiddlerwoaroof** [comment]
@nicolo-ribaudo is this what you need?

<img width="1067" alt="image" src="https://user-images.githubusercontent.com/808745/50543099-08a20280-0b82-11e9-9153-256ea45542a6.png">

<img width="906" alt="image" src="https://user-images.githubusercontent.com/808745/50543101-15bef180-0b82-11e9-8858-dcaf6fd393ce.png">

**Comment by nicolo-ribaudo** [comment]
Yes thank you!
Out our curiosity, if you go to `https://unpkg.com/babel-standalone@6.26.0` in a new tab, does it 404?

**Comment by ReeganExE** [comment]
_"Cannot find "/index.js" in babel-standalone@6.26.0"_

![image](https://user-images.githubusercontent.com/7277418/50553798-d955d780-0ce0-11e9-831d-cd2c85ee9697.png)

**Comment by nicolo-ribaudo** [comment]
Thank you. It is a big with unpkg: `https://unpkg.com/babel-standalone@6.26.0` should redirect to `https://unpkg.com/babel-standalone@6.26.0/babel.js`. I'll report it to them and keep you updated.

**Comment by nicolo-ribaudo** [comment]
Thank you all for your help. I'm marking all the comments on this issue as off-topic since this is about upgrading the Babel version in the repl. If you have anything else to say, please use https://github.com/babel/website/issues/1923

**Comment by aguibou32** [comment]
@ricardobeat Thank you it worked for me !
