### ISSUE TITLE
An error occurred while loading Babel :(

### ISSUE THREAD

**Issue by zy445566** [babel/website#1929]
![1](https://user-images.githubusercontent.com/14976489/50410617-1c253480-0835-11e9-9127-30350831703b.png)
url:https://babeljs.io/repl
cdn url:https://unpkg.com/babel-standalone@6.26.0/index.js

**Comment by nicolo-ribaudo** [comment]
Could you provide what I asked for at https://github.com/babel/babel/issues/9223#issuecomment-449360287?

**Comment by zy445566** [comment]
@nicolo-ribaudo 
I don't know why, but now it's ok。

**Comment by aguibou32** [comment]
Im having the same error "An error occurred while loading Babel :("
How did you fix it ??

**Comment by nicolo-ribaudo** [comment]
Not fixed yet - #1923

In the meantime you can use https://babeljs.io/build/master
