### ISSUE TITLE
Unable to run project on windows

### ISSUE THREAD

**Issue by saranshkataria** [babel/website#1931]
When I try and run the setup locally, I keep getting errors. A couple of initial ones were that NODE-ENV cannot be set directly in windows, it is used as SET NODE_ENV=production. Similarly, cp does not exist in windows. It should be -cmd copy and so on. Not sure if a third party package is used for windows checks or how it should work ideally, would be happy to send in PR's if get some help in pointing towards the right direction.

**Comment by xtuc** [comment]
Where did you see `NODE-ENV`? it should be `NODE_ENV `.

I agree that we should use something portable, Node based. Do you have a suggestion?

**Comment by nicolo-ribaudo** [comment]
Would something like `cygwin` or `msys2` work to setup babel on windows?

**Comment by saranshkataria** [comment]
WSL and cygwin would be workarounds, not solving the exact solution. I agree with @xtuc that it should be something node based. [Cross Env](https://www.npmjs.com/package/cross-env) is one possible solution which I have found that seems to work across platforms. 

For copying, webpack-copy-plugin should do the job I think?
