### ISSUE TITLE
@babel/traverse documentation needs improvement

### ISSUE THREAD

**Issue by oyilmaztekin** [babel/website#1934]
We can use the `traverse` method with the `enter` method and also the object property name like `FunctionDeclaration` regarding **@babel/types**. There is no information about this usage in this repo besides babel-handbook that you refer. 

```javascript
traverse(ast, {
    FunctionDeclaration: function(path) {
             path.node.id.name = "x";
    }
})
```
I want to add this usage and its explanation if you allow.

https://github.com/babel/website/blob/master/docs/traverse.md

**Comment by suchipi** [comment]
Yes please!

**Comment by oyilmaztekin** [comment]
I created the [**PR**](https://github.com/babel/website/pull/1938) for this issue but I cannot see changes at the [deploy preview](https://deploy-preview-1938--babel.netlify.com). Have I done something wrong?

**Comment by suchipi** [comment]
Hmm, I don't know why it's not working :( someone else might

**Comment by oyilmaztekin** [comment]
the traverse.MD file in versioned_docs/version-7.0.0 has been changed too. Now problem solved. 🙂
