### ISSUE TITLE
yarn.lock missing in .gitignore

### ISSUE THREAD

**Issue by oyilmaztekin** [babel/website#1939]
Local logs are blocking by .gitignore. But there is no rule defined about yarn logs. It needs to be added to .gitignore.

**Comment by nicolo-ribaudo** [comment]
`yarn.lock` and `package-lock.json` should be committed, not ignored.

**Comment by oyilmaztekin** [comment]
@nicolo-ribaudo I see. So you're ignoring only the npm logs in [.gitignore](https://github.com/babel/website/blob/master/.gitignore#L33).

**Comment by nicolo-ribaudo** [comment]
It is because this repository is meant to be used with `yarn install`. Having both of them can only lead to things getting out of sync.

**Comment by oyilmaztekin** [comment]
Thank you for the information.

**Comment by oyilmaztekin** [comment]
I found a good explanation [here] (https://www.engineyard.com/blog/composer-its-all-about-the-lock-file) which explains clearly why we need the *.lock file in our project.
