### ISSUE TITLE
On any syntax proposal page, recommend using the proposal plugin

### ISSUE THREAD

**Issue by hzoo** [babel/website#1949]
Via: https://twitter.com/cassidoo/status/1085350422884245504

I thought we did this before but we don't (or it got removed when we moved the docs repo)? **EDIT**: yeah we did! https://old.babeljs.io/docs/plugins/syntax-object-rest-spread/

![image](https://user-images.githubusercontent.com/588473/51224668-fe6b5c80-1914-11e9-91b7-cee22f455199.png)

Under: https://github.com/babel/website/blob/master/docs
- https://github.com/babel/website/blob/master/docs/plugin-syntax-optional-chaining.md
- https://babeljs.io/docs/en/babel-plugin-syntax-optional-chaining

doesn't really say anything at all. We don't actually want most people to ever need to install/use these syntax plugins since what they want is the "proposal" plugins. So we should add a comment at the beginning of all of these to link to the proposal plugins that actually compile the code vs. just turning on the syntax (I've suggested removing the syntax plugins but that's another story).

If it's included in preset-env, we should mention you don't need it at all then

**Comment by nicolo-ribaudo** [comment]
Exactly :+1:
Also, when you will commit the changes, it will probably also update the old docs automatically

**Comment by hzoo** [comment]
I would change the wording "If you want to actually be able to compile" seems wordy. I can't really think of a reason you would normally ever use a syntax plugin anyway honestly, only if it's a syntax that will be compiled by something else (webpack) so like dynamic-import. But there we should just do it for you in babel-loader.

**Comment by existentialism** [comment]
Maybe something like:

> It's unlikely you want to directly use this plugin directly as it only enables Babel to parse this syntax. You probably want to use <link to proposal/transform> to _both_ parse and transform this syntax.

**Comment by doms** [comment]
> I would change the wording "If you want to actually be able to compile" seems wordy.

That's true, I was just trying to phrase an example of what I would be attempting!

> Maybe something like:
>    It's unlikely you want to directly use this plugin directly as it only enables > Babel to parse this syntax. Instead, use <link to proposal/transform> to both parse and transform this syntax.

Oooh, this sounds good, I'll use this!

**Comment by doms** [comment]
@hzoo @existentialism 

Just about done with the task, and have a few questions!

Per the [contributing guide](https://github.com/babel/website#contributing-to-the-website), for every change in `docs/`, should I also be updating `versioned-docs/` ? 

If yes, would it be `7.0.0` (since that directory has all the files that I've made changes to in `docs/`) ?
