### ISSUE TITLE
REPL: Plugin @babel/plugin-proposal-optional-chaining could not be loaded

### ISSUE THREAD

**Issue by dimitarnestorov** [babel/website#1968]
After adding `@babel/plugin-proposal-optional-chaining` all I get is this:
![image](https://user-images.githubusercontent.com/8790386/52732511-147a4480-2fc9-11e9-9c64-1fbdbdcd3c50.png)

**Comment by nicolo-ribaudo** [comment]
Bundle.run gives the following error: https://bundle.run/@babel/plugin-proposal-optional-chaining@7.2.0
