### ISSUE TITLE
Add documentation for Partial Application Syntax: Stage 1

### ISSUE THREAD

**Issue by existentialism** [babel/website#1974]
Ref: https://github.com/babel/babel/pull/9343, https://github.com/babel/babel/pull/9474

- [ ] @babel/parser - Add `partialApplication` plugin
- [ ] @babel/types
- [ ] @babel/plugin-syntax-partial-application
- [ ] @babel/plugin-proposal-partial-application

**Comment by JLHwung** [comment]
Fixed in #1980
