### ISSUE TITLE
Hard to tell which page you're on

### ISSUE THREAD

**Issue by ewolfe** [babel/website#1985]
I want to propose tweaking the CSS of the active item to make it more obvious that it's the current page. Here's a sample before and after:

<img width="1680" alt="temp" src="https://user-images.githubusercontent.com/32533397/54075800-501ace00-4258-11e9-94d7-6ea5caeb55e9.png">

I'd be happy to open a pull request to implement this.

**Comment by loganfsmyth** [comment]
Looks good to me!

**Comment by ewolfe** [comment]
I realized it might be better to make this change upstream with docusaurus. I'll close this and go open a pull request there 😀
