### ISSUE TITLE
link to sprockets integration is incorrect

### ISSUE THREAD

**Issue by localhostdotdev** [babel/website#2017]
page: https://babeljs.io/docs/en/next/tools/rails/usage
corresponding file: https://github.com/babel/website/blob/master/docs/tools/rails/usage.md

links to https://babeljs.io/docs/en/next/tools/rails/usage#installation,

actual html:

```html
<a href="#installation" onclick="event.preventDefault(); document.querySelector('.tools-button[data-title=sprockets]').click()">integrating babel with sprockets</a>
```

js error:

```
usage:26 Uncaught TypeError: Cannot read property 'click' of null
    at HTMLAnchorElement.onclick (usage:26)
```

there is no `.tools-button` on the page.

nothing on archive.org

would be cool to have a way to integrate without webpacker, anyway https://github.com/Shopify/sprockets-commoner is unmaintained 

there are other projects:

- https://github.com/rmacklin/sprockets-bumble_d (updated 3 months ago)
- https://github.com/fnando/babel-schmooze-sprockets (updated 3 years ago)

anyway, just mentioning it

**Comment by microbouji** [comment]
Thanks for reporting. Do you remember how you got to that page?

It is unintended for that md file to be accessible via https://babeljs.io/docs/en/next/tools/rails/usage. It was only meant to be internally used to populate the [setup page](https://babeljs.io/setup). There you can find a separate section for sprockets which uses one of the newer projects.

I guess the easiest way for us to fix this will be to move the `tools` folder out of `docs`.

**Comment by localhostdotdev** [comment]
I think from googling "babel sprockets rails":

<img width="300" alt="Screen Shot 2019-05-06 at 2 24 35 PM" src="https://user-images.githubusercontent.com/47308085/57224769-b6c72880-700a-11e9-927d-8629b6ad1f98.png">

oh cool so `sprockets-bumble_d` is the recommended way
