### ISSUE TITLE
What a fag: Please be respectful when interacting with other people.

### ISSUE THREAD

**Issue by cs1717c** [babel/website#2026]
Please be respectful when interacting with other people.

_Originally posted by @nicolo-ribaudo in https://github.com/babel/website/pull/2024#issuecomment-491809569_

**Comment by DVLP** [comment]
You're spreading misinformation that "let is new var" which is mindlessly copied by bloggers. Yeah, you can silence my opinion but it will always be visible as neglected in git history and my fork during judgement day.

**Comment by loganfsmyth** [comment]
@DVLP We are not silencing your opinion, but we are not required to agree with your, take the actions you demand of us, or provide you a platform for your opinions. Your initial post was extremely pushy and confontational so it was unsurprisingly ignored and closed.
