### ISSUE TITLE
Information regarding @babel/polyfill deprecation unlisted in docs

### ISSUE THREAD

**Issue by cjones26** [babel/website#2039]
After implementing @babel/polyfill in our application, we ended up discovering the following blog post:

[https://babeljs.io/blog/2019/03/19/7.4.0](https://babeljs.io/blog/2019/03/19/7.4.0)

Which states:

```
@babel/polyfill isn't a plugin or preset, but a runtime package: if we added an option to switch between core-js@2 and core-js@3, both the package versions would need to be included in your bundle. For this reason, we decided to deprecate it: you now should load core-js for polyfills, and regenerator-runtime/runtime if you are transforming generators:

// before
import "@babel/polyfill";

// after
import "core-js/stable";
import "regenerator-runtime/runtime";

This gives you the ability to load any version you want, and to update those two package independently.

In case you are interested, you should check the old source of @babel/polyfill for core-js@2: packages/babel-polyfill/src/index.js.
```

The core-js team also mentions this in the document here:

[https://github.com/zloirock/core-js/blob/master/docs/2019-03-19-core-js-3-babel-and-a-look-into-the-future.md#babel](https://github.com/zloirock/core-js/blob/master/docs/2019-03-19-core-js-3-babel-and-a-look-into-the-future.md#babel)

Unfortunately, none of this information is listed anywhere in the @babel/polyfill documentation [https://github.com/babel/website/blob/master/docs/polyfill.md](https://github.com/babel/website/blob/master/docs/polyfill.md).

I figured this is something which should be mentioned so that others aren't incorrectly integrating @babel/polyfill, as the only reason we discovered this was due to a strange error we were receiving regarding core-js.  After implementing core-js@3.1.3 & regenerator-runtime@0.13.2, all of our issues were resolved.

**Comment by existentialism** [comment]
@cjones26 

It's there:

![image](https://user-images.githubusercontent.com/56288/58832859-7eb90280-8615-11e9-8559-a9675fa9569a.png)

But it looks like it's not being rendered out by docusaurus... will look into it in a bit.
