### ISSUE TITLE
Document `@babel/transform-runtime` `version` option

### ISSUE THREAD

**Issue by nicolo-ribaudo** [babel/website#2055]
https://github.com/babel/babel/blob/406a65c894624f8d07d6642d23c55b9a04197a75/packages/babel-plugin-transform-runtime/src/index.js#L42

**Comment by esprehn** [comment]
Is it possible to get this merged? It's a footgun right now that folks end up with the objectSpread2 helper inlined into every module that uses spread which increases the resulting JS size. If you have thousands of React components that adds up quite lot. It took a lot of digging to find the linked PR and the docs issue to realize we need a PR like https://github.com/meteor/babel/commit/49e13e75df591a9fda83e042de460cca97af924a

Also separately it seems bad that every project needs to do that PR to avoid increased bundle size. Is it possible to do something more automatic?
