### ISSUE TITLE
Why not just "?" for the plugin-proposal-optional-chaining operator?

### ISSUE THREAD

**Issue by GeorgeCalvert** [babel/website#2069]
The proposed operator for optional-chaining is `?.`, affording syntax like `myObject?.[myVariableProperty]`.  Why not simply the `?`?  Lookahead should see `?` followed by any operator as optional chaining.

**Comment by existentialism** [comment]
@GeorgeCalvert you'll want to head over to https://github.com/tc39/proposal-optional-chaining for a bit of explanation and discussion, as Babel just has an implementation of what's been proposed.

**Comment by GeorgeCalvert** [comment]
@existentialism -- thanks for the referral.
