### ISSUE TITLE
Docs: `babel-plugin-transform-member-expression-literals` and `babel-plugin-transform-property-literals` reference the wrong package

### ISSUE THREAD

**Issue by k-grube** [babel/website#2076]
From here:
https://babeljs.io/docs/en/plugins

ES3 section 
https://babeljs.io/docs/en/babel-plugin-transform-member-expression-literals 
https://babeljs.io/docs/en/babel-plugin-transform-property-literals

These should reference `@babel/transform-member-expression-literals ` and `@babel/transform-property-literals`

**Comment by microbouji** [comment]
Seems like this was fixed in #2087
