### ISSUE TITLE
Does any of the babel presets include @babel/plugin-proposal-class-properties?

### ISSUE THREAD

**Issue by mjangir** [babel/website#2090]
Does any of the babel presets include plugin `@babel/plugin-proposal-class-properties` or we just have to install it separately and configure with babelrc? Also how is it decided which plugins should be bundled in a preset and which are not?

**Comment by nicolo-ribaudo** [comment]
Official presets only included standard ECMAScript features (class properties are still a proposal).
You can create a custom preset, or search an existing one on npm.
