### ISSUE TITLE
VSCode syntax highlighting extenshion link broken, returns 404

### ISSUE THREAD

**Issue by tjcwilk** [babel/website#2167]
In the babel documentation, there is a page about code editors and syntax highlighting, https://babeljs.io/docs/en/editors/.

In the section for VS Code, there is a link to a recommended extenshion for babel syntqc highlighting. The link is broken, and returns a 404. This extenshion does not exist in the visual studio marketplace. ref: https://marketplace.visualstudio.com/items?itemName=joshpeng.sublime-babel-vscode)

**Comment by tjcwilk** [comment]
from looking around the variouse babel VSCode extenshions, i think this one could potentially be the latest for the one previosly linked - https://marketplace.visualstudio.com/items?itemName=mgmcdermott.vscode-language-babel.

Suggestion would be to replace the broken 404 link, with this one.

**Comment by JLHwung** [comment]
@tjcwilk LGTM, PR is welcome.
