### ISSUE TITLE
Can't load plugins in playground

### ISSUE THREAD

**Issue by eps1lon** [babel/website#2230]
1. Goto https://babeljs.io/repl
2. Expand "Plugins"
3. Click "Add plugin"
4. Click any plugin suggested
5. Error "Plugin @babel/plugin-transform-modules-commonjs could not be loaded"

Network requests starting with step 3:

![Screenshot from 2020-04-23 17-06-46](https://user-images.githubusercontent.com/12292047/80115322-e6a56e00-8584-11ea-9354-4e24c2a146bf.png)

Chrome 81 on Ubuntu 18.04

**Comment by JLHwung** [comment]
This is a known defect after we temporarily switch to `unpkg.com` because `bundle.run` is not available, see https://github.com/babel/website/pull/2228#pullrequestreview-396821658.

**Comment by eps1lon** [comment]
> As a workaround, please use the stage presets if the plugin is already included.

I wanted to test options for specific plugins so that wouldn't help. Though I'm not sure if I can even specify options for each plugin individually.

**Comment by JLHwung** [comment]
> specify options for each plugin individually.

AFAIK the REPL does not support plugin specific options.

**Comment by JLHwung** [comment]
This issue is now fixed by #2237 .
