### ISSUE TITLE
add plugin documentation for babel.config.js files to https://babeljs.io/docs

### ISSUE THREAD

**Issue by csdfgraham** [babel/website#2231]
How do you configure a babel plugin in a babel.config.js file:

e.g https://babeljs.io/docs/en/babel-plugin-transform-remove-console doesn't mention the configuration required for a babel.config.js file, where would the configuration fit into a babel.config.js: for example:

```
module.exports = {
    presets: [
        '@babel/preset-env',
        '@babel/preset-react'
    ],
    plugins : [
        '@babel/plugin-proposal-class-properties'
    ],
    env: {
        "test": {
            "plugins": ["@babel/plugin-transform-runtime"]
        }
    }
};
```

**Comment by hzoo** [comment]
Probably tried it already, but yes you can add the "babel-plugin-transform-remove-console" assuming it was installed via npm/yarn already to the plugins option where needed. I think that plugin in particular wasn't updated for v7, so it might not work

```js
module.exports = {
    presets: [
        '@babel/preset-env',
        '@babel/preset-react'
    ],
    plugins : [
        '@babel/plugin-proposal-class-properties',
        'babel-plugin-transform-remove-console'
    ],
    env: {
        "test": {
            "plugins": ["@babel/plugin-transform-runtime"]
        }
    }
};
```
