### ISSUE TITLE
Avatars in "Our top sponsors are shown below!" in README.md do not load

### ISSUE THREAD

**Issue by Daniel-Mietchen** [babel/website#2248]
## Bug Report

**Current Behavior**
<img width="909" alt="Screen Shot 2020-05-13 at 11 29 11" src="https://user-images.githubusercontent.com/465923/81833162-60d66c00-950d-11ea-8ede-d1e515d6b79b.png">

Looks like the underlying images at addresses like
https://opencollective.com/babel/sponsor/14/avatar.svg
are gone. I checked https://opencollective.com/babel but could not find a suitable replacement using a similar URL pattern.

**Comment by Daniel-Mietchen** [comment]
Currently,
> ```
> curl --HEAD https://opencollective.com/babel/sponsor/14/avatar.svg
> ```
gives:

> HTTP/2 503 
> date: Wed, 13 May 2020 17:33:30 GMT
> content-type: text/html; charset=UTF-8
> x-frame-options: SAMEORIGIN
> set-cookie: __cfduid=dc5ee38b8bfe59d1619eff2d341fa4e371589391210; expires=Fri, 12-Jun-20 17:33:30 GMT; path=/; domain=.opencollective.com; HttpOnly; SameSite=Lax; Secure
> cache-control: no-cache
> expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
> server: cloudflare
> cf-ray: 592e1ffa1b532484-FRA
> cf-request-id: 02b0b25053000024848cb78200000001
>

**Comment by JLHwung** [comment]
Closing this as it can not be reprodueced.
