### ISSUE TITLE
Babel repl not working in safari

### ISSUE THREAD

**Issue by brainkim** [babel/website#2254]
![Screen Shot 2020-05-17 at 3 46 56 AM](https://user-images.githubusercontent.com/2996754/82138785-185ecd00-97f1-11ea-83d8-8314e0be108b.png)

I’m stuck on this screen and opening the console shows me the following error:

SyntaxError: Invalid regular expression: range out of order in character class

I don’t have more information about the error.
Safari version 13.0.5
MacOS Mojave 10.14.6

**Comment by nicolo-ribaudo** [comment]
Does it tell you which is the invalid regex?

**Comment by brainkim** [comment]
![Screen Shot 2020-05-17 at 4 10 40 AM](https://user-images.githubusercontent.com/2996754/82139228-675a3180-97f4-11ea-8d31-39427b76ec30.png)
this is what I see :( safari is notorious for having sourcemaps and stack traces not work

**Comment by JLHwung** [comment]
I believe it is due to an upstream JSC bug: https://bugs.webkit.org/show_bug.cgi?id=212725
