### ISSUE TITLE
Please leave the politics out of it

### ISSUE THREAD

**Issue by Nettsentrisk** [babel/website#2266]
I'm trying to do my job, and trying to read documentation for BabelJS, and the whole web site is now "offline out of respect for George Floyd and all the other victims of police violence in the Black community."

How does preventing everyone using BabelJS, including black developers, from accessing your web site, help George Floyd or anyone else, in the slightest? It helps no one. Fundraising for various related things can be done without shutting people off. 

In fact, doing it this way probably leads to less people donating because you are violating several UX principles, that is, preventing a user from accomplishing the task they went to the web site for, and presenting the user with a completely different task than the one they were looking for.

You are not solving any problems, you are only preventing good people from doing their jobs, thereby punishing people who have done nothing wrong, who are sympathetic to those who are affected by police violence, yet who are being constantly bombarded with this everywhere they go. It's all over the news, it's all over social media.

There is a time and place for everything. Politics is seeping into everything, everywhere, these days. Can we at least give it a rest in our profession, that has absolutely nothing to do with this specific problem? Or is that too much to ask?

**Comment by existentialism** [comment]
@Nettsentrisk did you miss the link at the bottom?

![image](https://user-images.githubusercontent.com/56288/83641257-e8deed00-a572-11ea-8028-6641970c0456.png)

> It helps no one.

The core team does not agree.

> In fact, doing it this way probably leads to less people donating

If people no longer want to donate because our team is making a statement, then so be it... we are _always_ grateful for those who have and those who continue to support the project in any way.

> Can we at least give it a rest in our profession

The core team does not agree.

**Comment by Nettsentrisk** [comment]
Does your disagreement come with actual facts or arguments, or is your need to signal how awesome you are to the world suffice?

Yes, I can wade through a bunch of markdown files, that's really useful, thanks for being such a help. That will certainly help bring George Floyd back to life!

**Comment by lyserge** [comment]
I was inconvenienced by this decision too. I completely support it.

> Politics is seeping into everything, everywhere, these days.

```
> 'civil rights' == 'politics'
false
```

> Can we at least give it a rest in our profession, that has absolutely nothing to do with this specific problem?

https://www.latimes.com/business/technology/story/2020-06-02/tech-companies-with-police-contracts-and-poor-diversity-records-issue-statements-of-solidarity-with-george-floyd-protesters

https://www.wired.com/story/five-years-tech-diversity-reports-little-progress/

**Comment by nicolo-ribaudo** [comment]
https://deploy-preview-2264--babel.netlify.app/

This is a mirror to the docs. Use it as you prefer.
That said, if you disagree with our belief that some things are more important to tech and that it's ok to give visibility to what is most important for us, we are not forcing you to use our software 🤷‍♂️

EDIT: Thanks @lyserge!

**Comment by Nettsentrisk** [comment]
> 'civil rights' == 'politics'
false

What does preventing us from reading BabelJS documentation have to do with civil rights? Politics is the act and process of making choices on how to affect people, such as preventing people from accessing knowledge. 

You're not giving anyone civil rights by preventing people from reading technical documentation of something that has nothing to do with those civil rights.

Or is BabelJS somehow at fault for what happened to George Floyd? Have you all lost your minds? None of this makes any sense, it's gibberish.

This is essentially burning a book to accomplish nothing for the alleged purpose of burning it.

**Comment by alexcosmin** [comment]
When is the website expected to go back online? :)

**Comment by nicolo-ribaudo** [comment]
@alexcosmin We'll post here an update as soon as we have a final answer.

**Comment by Nettsentrisk** [comment]
>That said, if you disagree with our belief that some things are more important than tech and that it's ok to give visibility to what is most important for us, we are not forcing you to use our software 🤷‍♂️

In that case, you can't ever put the site back online, because then you're saying that the thing you now say is too important to show the site, is not as important anymore?

This is a false dilemma. There's no conflict between this issue being important, more important than any random list of other things, and letting people read the documentation for this package. It's a complete non-sequitur.

**Comment by razius** [comment]
@alexcosmin when Floyd is brought back to life.

**Comment by nicolo-ribaudo** [comment]
I'm locking this issue. The website will be back 24 hours after we took it down (i.e. in about 8-9 hours)
