### ISSUE TITLE
Replace 404 page with BLM message?

### ISSUE THREAD

**Issue by joliss** [babel/website#2267]
I was confused when I followed a link and it threw a [non-descriptive 404 page](https://babeljs.io/docs/en/babel-plugin-transform-class-properties/). If there's a way to override the 404 page, may I suggest replacing it with the BLM main page as well?

P.S. Great work! 👍

**Comment by hzoo** [comment]
Done, good catch! (just needed to add a 404.html somewhere, as we just replaced the old site)
