### ISSUE TITLE
Setup documentation typo with babel-register moved to @babel org

### ISSUE THREAD

**Issue by maxime-helen** [babel/website#2305]
## Bug Report

- [X] I would like to work on a fix!

**Current behavior**

Following current setup documentation from [https://babeljs.io/en/setup#installation](url) with Mocha leads to a npm conflict between `@babel/core` and `babel-core` packages

```
error: bundling failed: Error: Requires Babel "^7.0.0-0", but was
loaded with "6.26.3". If you are sure you have a compatible version of
@babel/core, it is likely that something in your build process is
loading the wrong version. Inspect the stack trace of this error to
look for the first entry that doesn't mention "@babel/core" or
"babel-core" to see what is calling Babel.
```

See [stackoverflow post](https://stackoverflow.com/questions/51873516/requires-babel-7-0-0-0-but-was-loaded-with-6-26-3)

`babel-register` depends on deprecated `babel-core` that isn't compatible with `@babel/core` dependency

**Expected behavior**
No error/conflict should be happening

**Environment**

- Babel version(s): ^7.0.0
- Node/npm version: v12.18.0, v6.14.4
- OS: OSX 10.13.4
- Monorepo: no
- How you are using Babel: `register`

**Possible Solution**

Update documentation to:

> Installation
> 
> ```
> npm install --save-dev @babel/register
> ```
> 
> Usage
> 
> In your package.json file make the following changes:
> 
> ```
> {
>   "scripts": {
>     "test": "mocha --require @babel/register"
>   }
> }
> ```
> 
> 
>   [1]: https://babeljs.io/en/setup#installation
>

**Comment by JLHwung** [comment]
These instructions are in https://github.com/babel/website/tree/master/website/data/tools/mocha, PR is welcome!
