### ISSUE TITLE
[docs: https://babeljs.io/docs/en/config-files] A hash-change is not working correctly

### ISSUE THREAD

**Issue by lidqqq** [babel/website#2323]
I tried to open internal link `6.x vs 7.x .babelrc loading` at right side menu links in below page, but it was not able to work.
https://babeljs.io/docs/en/config-files

Then, I found a `-` character which may affect this behavior at URL suffix.

Does anyone know about why it happened and how to resolve that ?

![スクリーンショット 2020-08-24 9 20 38](https://user-images.githubusercontent.com/39523918/90992706-6eab8b00-e5ec-11ea-88dd-b2ae4fc44452.png)

**Comment by JLHwung** [comment]
@lidqqq Good catch! It is a docusaurus bug and will be fixed in #2324.

**Comment by lidqqq** [comment]
@JLHwungThanks for quick response and fixed !
