### ISSUE TITLE
404 on repl

### ISSUE THREAD

**Issue by Natetronn** [babel/website#2422]
I'm getting a 404 not found on https://babeljs.io/repl

![babel-404](https://user-images.githubusercontent.com/582149/99892225-99c36c00-2c27-11eb-90c1-add954f4f103.png)

**Comment by existentialism** [comment]
@Natetronn strange, loads fine for me? Do you get it immediately when going to https://babeljs.io/repl ?

**Comment by Natetronn** [comment]
@existentialism yes, very strange. And yes, I did. It was linked to from another site. I also tried going direct and the using the nav bar item.

I first cleared all babel history but, that didn't help, so I cleared all my cache and data and now it's working fine. I'm not sure why it came to that but, it's working now so that's good.
