### ISSUE TITLE
Evaluate not working

### ISSUE THREAD

**Issue by serdec** [babel/website#2427]
Hi everybody,

i am experiencing a problem with the evaluate function. It remains deactivate, no matter what browser i am using. I have tried on firefox 83.0 both in private mode and normal mode. Same thing on Chrome.

In the console i get the following error

GET https://bundle.run/@babel/polyfill@7 net::ERR_ABORTED 502

**Comment by JLHwung** [comment]
cc @xtuc

**Comment by xtuc** [comment]
sorry about that. i fixed

**Comment by serdec** [comment]
That was fast. Thank you so much!

**Comment by serdec** [comment]
Hi guys,

the evaluate function is not working, there is a 502 error from the server

**Comment by xtuc** [comment]
I fixed it again

**Comment by djmisterjon** [comment]
> I fixed it again

not work ! there is a 502 error from the server
![image](https://user-images.githubusercontent.com/24865815/120061812-e8b1ea00-c02c-11eb-99b7-bb0e87f6c642.png)

**Comment by xtuc** [comment]
@djmisterjon  I fixed the issue again, sorry for the inconvenience.
