### ISSUE TITLE
Assumptions page examples aren't loading

### ISSUE THREAD

**Issue by Alexendoo** [babel/website#2456]
Hello there

On https://babeljs.io/assumptions the examples under each rule don't load, tested in firefox and chrome

![image](https://user-images.githubusercontent.com/1830331/108854774-23e0ef00-75e0-11eb-91e4-0d8623803b16.png)

Console shows these errors, repeated ~20 times each

```
state.js:864 Uncaught TypeError: Cannot read property 'extension' of undefined
    at inner (state.js:864)
    at inner (state.js:864)
    at inner (state.js:847)
    at inner (state.js:864)
    at inner (state.js:847)
    at flatten (state.js:867)
    at Function.resolve (state.js:786)
    at Function.create (state.js:1262)
    at HTMLElement._createInputEditorState (mini-repl.js:217)
    at HTMLElement.connectedCallback (mini-repl.js:160)
inner @ state.js:864
inner @ state.js:864
inner @ state.js:847
inner @ state.js:864
inner @ state.js:847
flatten @ state.js:867
resolve @ state.js:786
create @ state.js:1262
_createInputEditorState @ mini-repl.js:217
connectedCallback @ mini-repl.js:160
AssumptionDocs @ assumption-docs.js:23
(anonymous) @ assumption-docs.js:54
```

```
mini-repl.js:182 Uncaught TypeError: Cannot read property 'setState' of undefined
    at HTMLElement.setInput (mini-repl.js:182)
    at new AssumptionDocs (assumption-docs.js:29)
    at assumption-docs.js:54
setInput @ mini-repl.js:182
AssumptionDocs @ assumption-docs.js:29
(anonymous) @ assumption-docs.js:54
```

**Comment by JLHwung** [comment]
Can confirm it is broken because of bundling issues in skypack.dev.

![image](https://user-images.githubusercontent.com/3607926/108858616-5d9eff00-75ba-11eb-9560-70592b8065bc.png)

`FacetProvider` is likely bundled twice in the modules.

**Comment by nicolo-ribaudo** [comment]
Maybe it's because we have multiple entry points:
https://github.com/babel/website/blob/95dfbaca14a81bdeca52c5695f6cba6d26d486b0/website/static/js/components/mini-repl.js#L4-L10

**Comment by JLHwung** [comment]
Yeah. Guess we have to bundle `@codemirror`.

**Comment by fedeci** [comment]
Still not loading on Safari
<img width="1792" alt="Screen" src="https://user-images.githubusercontent.com/38510000/120973327-11de2300-c76f-11eb-8e11-b636489b1e13.png">
