### ISSUE TITLE
Docs: babel-present-env and stage-x proposals

### ISSUE THREAD

**Issue by thernstig** [babel/website#2483]
## Feature Request

**Is your feature request related to a problem?**
Reading https://babeljs.io/docs/en/babel-preset-env it says:

> We leverage these data sources to maintain [mappings of which version](https://github.com/babel/babel/blob/master/packages/babel-compat-data/data/plugins.json) of our supported target environments gained support > of a JavaScript syntax or browser feature, as well as a mapping of those syntaxes and features to Babel transform plugins and > core-js polyfills.

> It is important to note that @babel/preset-env does not support stage-x plugins.

The note about `stage-x` plugins makes it sound like no plugins of e.g. stage 3 would exist in `present-env`. Yet looking at the linked docs at https://github.com/babel/babel/blob/master/packages/babel-compat-data/data/plugins.json shows `proposal-class-properties` which is only in stage 3, see https://github.com/tc39/proposal-class-fields, is a supported stage 3 plugin.

**Describe the solution you'd like**
The docs should be updated to not make a note about "_does not support `stage-x` plugins_" to say "not all". Or something else. In addition, stage 4 are supported, but yet they fall under `stage-x`, so saying "not stage-x" seems overall to be incorrect.

In addition https://babeljs.io/docs/en/babel-plugin-proposal-class-properties does not mention it is in `@babel/preset-env` but many others do just that, like https://babeljs.io/docs/en/babel-plugin-proposal-object-rest-spread (at the top of the docs).

**Comment by hzoo** [comment]
Thanks for the report! I just modified some of those pages a few days ago so I probably missed it https://github.com/babel/website/pull/2477, can make a PR to clarify

**Comment by thernstig** [comment]
I did find `shippedProposals` when reading further at https://babeljs.io/docs/en/babel-preset-env#shippedproposals

So that comment about "_does not support stage-x plugins_" is not entirely true then.

**Comment by hzoo** [comment]
yeah it's a bit nuanced, I think the intent is to explain that we want to allow targets against browsers that implement whatever version of javascript. If there is a proposal that a browser supports then we can target it, otherwise (especially for anything Stage 2 or less) it would always be compiled. We added shippedProposals a bit later, idea was that we want Babel to transform the minimum amount, so if it was still Stage 3 and you only target'd that browser in development you wouldn't need to transform it

**Comment by hzoo** [comment]
Yeah looks like I missed one or two, sorry for the confusion!
