### ISSUE TITLE
Decorator proposal edit

### ISSUE THREAD

**Issue by Thomas-Langlais** [babel/website#2507]
## Description
I find that the [@babel/plugin-proposal-decorators](https://github.com/babel/website/blob/master/docs/plugin-proposal-decorators.md) documentation is not accurate considering there is an [open issue](https://github.com/babel/babel/issues/12654) discussing this in further detail. I think this should be reflected in the web documentation until the plugin implements the stage 2 proposal more accurately.

## Solution
There should be a warning stating that the stage 2 implementation does not accurately follow the proposal.
Stating that using the legacy version might be a better alternative in the meantime.

I can make the changes, but I would like to hear from other first to see if this is a worthwhile change.

**Comment by JLHwung** [comment]
Implementation of the 2021-12 decorator proposal is tracked in #14004.
