### ISSUE TITLE
Add `assumptions` to repl

### ISSUE THREAD

**Issue by AjayPoshak** [babel/website#2532]
I would like to work on adding assumptions option to repl.  I have attached a screenshot of what I think should be the design.

<img width="320" alt="Screenshot 2021-05-16 at 10 57 55 AM" src="https://user-images.githubusercontent.com/7375457/118386520-a1435b00-b635-11eb-84d2-50721d8ce8fe.png">

**Comment by nicolo-ribaudo** [comment]
I like it!

**Comment by jojoski** [comment]
What is it

Sent from Yahoo Mail on Android 
 
  On Thu, May 20, 2021 at 7:19 PM, Nicolò ***@***.***> wrote:   


I like it!
