### ISSUE TITLE
Add Dark Mode 

### ISSUE THREAD

**Issue by tyonirwansyah** [babel/website#2546]
Adding a darkmode in the website would be nice.

**Comment by hzoo** [comment]
Is this something you'd want to add? It's possible https://v1.docusaurus.io/ has support, but I know https://docusaurus.io/ v2 has a toggle for it but i'd be a larger change to just upgrade

**Comment by thomasgilmore95** [comment]
Is this still up for grabs. I would like to work on this.

**Comment by Ashtaq** [comment]
Guys is there anything you want me to work on.

**Comment by JLHwung** [comment]
The dark mode has been implemented in https://github.com/babel/website/pull/2711.
