### ISSUE TITLE
REPL: please add pipeline proposal options: Hack, Elixir

### ISSUE THREAD

**Issue by lightmare** [babel/website#2552]
Currently it's kinda difficult to test experimental flavours in the REPL.

Alternatively, include the pipeline proposal value in URL.  This would probably be even more useful, as besides allowing sending links with pipeline flavour pre-selected, it would also allow me to put an unlisted value in there.

**Comment by JLHwung** [comment]
You can draft an REPL PR to this repo. Netlify will host a PR website, where you can have REPL attached to the babel standalone built from your Babel PR.

**Comment by lightmare** [comment]
@JLHwung Thank you. Figuring out how to attach it to Babel PR took me a while (at first I only changed `version=` in the URL, which didn't do anything), but got it working in the end.

**Comment by nicolo-ribaudo** [comment]
@lightmare Are you interested in opening an alternative to #2553 that adds Hack and removes Smart (since Hack has been added in 7.15.0) so that we can merge it to the main repl? Otherwise I can do it.

**Comment by lightmare** [comment]
I'll take a look. There are some new conflicts I haven't seen.

**Comment by lightmare** [comment]
New PR #2563
