### ISSUE TITLE
Commit from April 2021 is full of breaking documentation changes

### ISSUE THREAD

**Issue by nickshanks** [babel/website#2598]
[This commit](https://github.com/babel/website/commit/24588d64b8032b653ce959171865cdd87d6a29dc#diff-8afd9c53031161d581749064204cb32c063b54d7523f84c2dd0e39d7e3d0b0a0) is saturated with changes to the input and output samples which do not reflect the actual effects of that plug-in. Some of the changes are non-breaking, such as adding a final comma to the list of properties of an input object. Other changes such as the specific fragment linked above completly change the meaning of the sample code, and invalidate it. The original was correct. The changes look to have been generated by a code prettifier. The author has not manually checked them, and the code was not reviewed. I strongly recommend reverting the whole change set until each changed line can be verified one by one.

**Comment by JLHwung** [comment]
The fragment linked above has been fixed in #2670. Other changes look good to me.
