### ISSUE TITLE
scrollSpy: Can not find header element

### ISSUE THREAD

**Issue by TwiggyBuffalo** [babel/website#2600]
## Description
`scrollSpy`'s listener floods the console with the following error on [https://babeljs.io/docs/en/v7-migration](https://babeljs.io/docs/en/v7-migration) I suspect <a href="https://github.com/babel/website/blob/b31e5186d33a580cf152e1eec93d416630d338f6/docs/v7-migration.md?plain=1#L27">this link</a> is to blame. Heading over to the deprecated-yearly-presets page, it throws the same error with an id of undefined.

## Screenshot
<img width="776" alt="errors" src="https://user-images.githubusercontent.com/14329351/147577527-0655d780-350b-4fbc-9663-7b98706cfbbb.png" />

**Comment by JLHwung** [comment]
I can't reproduce this issue after upgrading to docusaurus 2. Feel free to reopen it if there are similar issues.
