### ISSUE TITLE
Suggestion to update image source of 'Sponsored by Zebra' in the main page. 

### ISSUE THREAD

**Issue by ahmetcakr** [babel/website#2602]
In the main page of website, one of photos(Sponsored by Zebra) under Base Support is not working .

**Comment by nicolo-ribaudo** [comment]
We automatically fetch the images from OpenCollective, but it looks like they don't have one :thinking:

**Comment by yadunandanbhat** [comment]
It's showing it now!

**Comment by JLHwung** [comment]
Can confirm it works.
