### ISSUE TITLE
Consider replacing the word „blacklisting”

### ISSUE THREAD

**Issue by Ryuno-Ki** [babel/website#2654]
The industry moved on to the term denylist or blocklist, which are easier to understand.

> This option is useful for "blacklisting" a transform like `@babel/plugin-transform-regenerator`.

Source: https://github.com/babel/website/blob/7690bd6fc6b801f7be9654e92eaf09fcf307d4da/docs/preset-env.md#exclude
Docs: https://babeljs.io/docs/en/babel-preset-env#exclude

**Comment by nicolo-ribaudo** [comment]
Oh thanks for catching this. We can replace it with _disabling_, or _excluding_. Would you like to open a PR?

**Comment by Ryuno-Ki** [comment]
Sure. #2655.
