### ISSUE TITLE
Dead anchor link at https://babeljs.io/docs/en/options#ineffective-browserslist-queries

### ISSUE THREAD

**Issue by Scott-Fischer** [babel/website#2658]
When attempting to debug an issue I was having related to my browserslist query inside of babel, I came across an anchor link in the documentation that does not appear to scroll the user to any other part of the page. It's the word "caveats" which can be found under the output targets section of the options page. (Screenshot below)

<img width="525" alt="image" src="https://user-images.githubusercontent.com/8835133/176906434-d58a707a-c1bc-4ddc-9d7c-7865f043677e.png">

This should be an easy fix, which I'd even be happy to contribute to. But as someone who isn't overly familiar with the babel docs, I'm not sure what this is supposed to be linking to. 

Does anyone know what this originally linked to?

**Comment by JLHwung** [comment]
Thanks for the head up. The caveat section should be linked to https://babeljs.io/docs/en/babel-preset-env#ineffective-browserslist-queries. It will be fixed in #2659.
