### ISSUE TITLE
Unable to use decorators in repl

### ISSUE THREAD

**Issue by trusktr** [babel/website#2677]
[example repl](https://babeljs.io/repl/#?browsers=chrome%20100&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=GYVwdgxgLglg9mABMOcAUECUiDeAoRRAJwFMoQikI8BfPPAAWogBsBDAZw8QDFVcaQA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Cstage-3%2Ctypescript&prettier=false&targets=&version=7.19.2&externalPlugins=&assumptions=%7B%7D)

I selected the `stage-3`. Shouldn't that enable the new stage 3 decorators?

**Comment by liuxingbaoyu** [comment]
fixed https://github.com/babel/website/pull/2718
