### ISSUE TITLE
"Built-ins" throws on REPL

### ISSUE THREAD

**Issue by fisker** [babel/website#2687]
```text
[BABEL] /repl.js: @babel/preset-env: The 'useBuiltIns' option must be either
    'false' (default) to indicate no polyfill,
    '"entry"' to indicate replacing the entry polyfill, or
    '"usage"' to import only used polyfills per file (While processing: "base$0")
```

[link](https://babeljs.io/repl#?browsers=ie%2011&build=&builtIns=usage&corejs=3.21&spec=false&loose=false&code_lz=GYexH4DoEMBcAoC0BGAlEA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=true&timeTravel=true&sourceType=module&lineWrap=true&presets=env%2Cstage-3&prettier=true&targets=&version=7.19.2&externalPlugins=&assumptions=%7B%7D)

**Comment by liuxingbaoyu** [comment]
Can you provide a link where it went wrong?

**Comment by fisker** [comment]
Added

**Comment by liuxingbaoyu** [comment]
Thanks for the report, the PR is waiting to be merged, you can temporarily use https://deploy-preview-2688--babel.netlify.app/

**Comment by fisker** [comment]
Thank you!
