### ISSUE TITLE
Configure redirects from `/en/` to `/`

### ISSUE THREAD

**Issue by harish-sethuraman** [babel/website#2735]
Related to https://github.com/reactjs/reactjs.org/issues/5633

Seems like some of the older URLs had `/en/` in the URL. Should we consider redirecting those to `/` to avoid older URLs throwing 404? 

we have `/docs/en/*` for redirects already. Should we handle the repl case separately? 
```
# Docusaurus v1 compat

/docs/en/* /docs/:splat
```

**Comment by JLHwung** [comment]
Yes, we should have redirected `/en/repl` to `/repl`. I didn't know that was even working before.
