### ISSUE TITLE
Update 'Twitter' to 'X' in footer of homepage

### ISSUE THREAD

**Issue by BishalJena** [babel/website#2932]
From this: 
<img width="228" alt="Screenshot 2024-08-02 at 9 07 13 PM" src="https://github.com/user-attachments/assets/2ab6db3e-0820-4f54-91d1-350686d0eceb">

to this:
<img width="230" alt="Screenshot 2024-08-02 at 9 07 33 PM" src="https://github.com/user-attachments/assets/9c582482-6ad9-4dae-b9af-c42e319053bf">

**Comment by BishalJena** [comment]
I can work on this issue quickly and raise a PR.

**Comment by nicolo-ribaudo** [comment]
Even though the official name is "X", I find "Twitter" in that list to be much more descriptive. Given that it's not a list of social networks (e.g. Facebook, Linkedin, X, Instagram), X could mean literally anything.

**Comment by BishalJena** [comment]
Let's keep the name as "Twitter" and just update the backlink from "twitter.com/babeljs" to "x.com/babeljs".
How about that?

**Comment by seaisbig** [comment]
make it as ''twitter/x''

**Comment by Shubhashish-Chakraborty** [comment]
## Please can i work on this issue!:

### I would like to update the URL from `twitter.com/babeljs` to `x.com/babeljs` to reflect the platform's rebranding.

### I propose offering the following three options for the text representation:

1. **X**
2. **X (Twitter)**
3. **X/Twitter**

## Kindly assign this task! I'll make the changes as mentioned. Let me know your preference, and I'll raise a PR!

![babelFix](https://github.com/user-attachments/assets/37388875-d71f-4238-8800-fa3b4c94ce16)

**Comment by nicolo-ribaudo** [comment]
I guess `X (Twitter)` is fine (with a space after the X), but please also link to our Bluesky account (https://bsky.app/profile/babel.dev/)

**Comment by Shubhashish-Chakraborty** [comment]
Alright Sir, thank you for assigning me the task! I’ll complete the work as soon as possible.
