### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by UnusualSoul** [babel/website#2934]
On the page, "[@babel/preset-react](https://babeljs.io/docs/babel-preset-react)", the link (under heading "Installation") "[Getting Started page](https://react.dev/docs/hello-world.html)" leads to a not found page.
![image](https://github.com/user-attachments/assets/434dffa2-0f8a-497d-9907-73a18bb9d7de)

**Comment by JLHwung** [comment]
Thank you for the report. I believe that link has been moved to https://react.dev/learn/installation, do you want to open a PR and update the link?
