### ISSUE TITLE
Document API's better

### ISSUE THREAD

**Issue by jmm** [babel/website#334]
This issue is to track a variety of items that are in need of more documentation and will be updated as time goes on. Items can be split off into their own issues as necessary. There's discussion of many of these items in slack.
# Public APIs

**NOTE**: To anyone reading this: There is some degree of speculation here about what is public API. This is not the documentation. None of this is confirmed public API until and unless it's documented.
- [ ] Path system
  - [ ] High-level concepts.
  - [ ] Context (`this`) in transformers.
  - [ ] Interface, e.g.:
    
    ``` js
    get()
    insertBefore()
    insertAfter()
    replaceWith()
    replaceWithMultiple()
    replaceWithSourceString()
    dangerouslyRemove()
    parentPath()
    addComment()
    traverse(visitor)
    ```
- [ ] Plugins
  - [ ] Interface for passing options.
  - [ ] Naming convention: `"babel-plugin-" + name`, e.g. `babel-plugin-foo`, is encouraged. Enables `$ babel --plugins foo` and aids in discoverability. If not following the convention it's encouraged to add `babel-plugin` to `package.json`'s `keyword` prop.
  - [ ] Interface of plugin argument (`babel`).
    - [ ] Access to options passed to `babel.transform()`?
  - [ ] Transformer (visitor) signature(s) (e.g. `node`, `parent`, `scope`, `file`).
    - [ ] Access to options passed to `babel.transform()`? Currently available via `this.state.opts` or `file.opts` -- intended to be public API?
    - [ ] `file.get()|file.set()`: Get / set data on file object, e.g. for communicating data between visitor methods. API will eventually provide each plugin state per file.
    - [ ] `file.addImport(as, from [, "absolute"])` Add an `import` declaration.
  - [ ] Acceptable `plugins` option element values: string, plugin function?, transformer instance?, ...?
  - [ ] String resolution algorithm, e.g can you do `plugins: ["foo/before", "foo/after"]`? Or perhaps better yet, make `Transformer` signature `(transformerKey, beforeTransformer, afterTransformer)`?
  - [ ] If distinction between internal and user transformers is removed, what will happen to `:before|after` behavior? See https://babeljs.slack.com/archives/plugins/p1434552346000236.
  - [ ] Scope
    - [ ] `scope` vs `this.scope`?
    - [ ] Undocumented methods: `hasGlobal()`, `getProgramParent()`, `noGlobals` param of `hasBinding()`.
  - [ ] Error handling: `throw this.errorWithNode("message")`
- [ ] `babel.types` node building methods / template plugin API (still under development).
- [ ] `babel.parse()` (see #290 /cc: @SevereOverfl0w).
- [ ] `babel.transform().ast` value.
  
    The current level of documentation of this is misleadingly non-specific. The presumption would be that `ast` is an ESTree AST where `ast.type`'s value is `Program`, but it is `File`. `ast` is an opaque data structure containing an ESTree AST at `ast.program`. Per @sebmck on slack the data structure is appropriate and the resolution is to codify that in ESTree.
- [ ] `canCompile()`

**Comment by hzoo** [comment]
`remove` was renamed to `dangerouslyRemove`

> Transformer (visitor) arguments (e.g. node, parent, ...?).
Looks like it's `node, parent, scope, state`? I see `node, parent, scope, file` in another context though

**Comment by jmm** [comment]
@hzoo 
> `remove` was renamed to `dangerouslyRemove`

Ok, ok, thanks -- I'll delete `remove` from that list.

> Looks like it's `node, parent, scope, state`? I see `node, parent, scope, file` in another context though

I've seen some of those, but I haven't had the chance to dig into it. Do you think I should edit those into my post for now as stubs?

**Comment by hzoo** [comment]
Since we don't have any api docs here maybe we could move this to the handbook instead. I was thinking we could just download it here and then render it from markdown.

**Comment by hzoo** [comment]
Moving to https://github.com/babel/website/issues/1628
