### ISSUE TITLE
REPL: Include Source Maps?

### ISSUE THREAD

**Issue by sparty02** [babel/website#65]
Thought:  Including source maps in the transpiled REPL output would allow browser debugging through the ES6 (REPL input) vs ES5 (REPL output) code.

**Comment by sparty02** [comment]
Note to self, I tried simply setting the sourceMap option when transforming:
```
transformed = to5.transform(code, {
        sourceMap : 'inline',
        experimental: options.experimental,
        playground: options.playground,
        loose: options.loose && "all",
        filename: 'repl'
      });
```
...which actually worked in Firefox, but not in Chrome or Safari.

**Comment by thejameskyle** [comment]
@sparty02 Are you working on creating a PR for this?

**Comment by sparty02** [comment]
@thejameskyle Yeah, I have one for the simple change I mentioned above, but it's flaky across browsers.  It doesn't cause any issues, but it doesn't work great either.

Some considerations:
* Should this be an option?  (I tend to think no, since it's more or less transparent)
* Is it important that the source maps do/don't display in the REPL output (i.e. maybe they should be 'attached' behind the scenes)
* Should this feature wait until a better cross browser solution is found?

**Comment by thejameskyle** [comment]
> Should this be an option?

No I don't think so.

> Is it important that the source maps do/don't display in the REPL output (i.e. maybe they should be 'attached' behind the scenes)

Yes that would be much better.

> Should this feature wait until a better cross browser solution is found?

Yeah, even if it's only enabling them in browsers we know will work (preferably via feature-detection if possible).

**Comment by jasonLaster** [comment]
Hmm, I might be able to take this on. We would like an easy way to quickly make some source map examples for [debugger-examples](https://devtools-html.github.io/debugger-examples/)

**Comment by hzoo** [comment]
Yeah I believe @developit already did something for the preact reply that we can do

**Comment by developit** [comment]
Yup:

https://github.com/developit/preact-www/blob/master/src/components/controllers/repl/worker.js#L36

**Comment by bvaughn** [comment]
Hey all 😄 Would love your thoughts on #1315 regarding how we should expose this in the UI.
